<?php
/**
 * @file
 * A chron module to create custom tables and load data from CouchDb into these tables.
 */

error_reporting(E_ALL);
ini_set("display_errors", 1);

/**
* Cron job is creating the queue cron job.
*
*/
function ajexportregs_cron() {

  $queue = DrupalQueue::get('ajexportregs');
  $queue->createItem("arg1");
}


/**
* Cron jobs info.
*
* @return array
*/
function ajexportregs_cron_queue_info()
{

    $queues = array();

    $queues['ajexportregs'] = array(
        'worker callback' => 'load_export_regs_worker',
        'time' => 300, // time in seconds, this is the duration that the job will be CALLED, e.g.
    // after it finish it will be called again until the time is up.
    );


   return $queues;
}

/**
 * The queue job worker. Query registration from couchDB descending and load them into mySQL database.
 *
 */
function load_export_regs_worker()
{
    $CHUNK_SIZE = 200;

 try{
    ajetllog_log("ajexportregs", "MESSAGE", "PROCESSING STARTED");
    global $base_url;
    $linesAry = array();

    ajexportregs_setModuleVariables();

    $regKeys = variable_get("ajRegKeys");

    // retrieve all registrations
    $req_url = 'http://localhost:5984/coconut/_design/coconut/_view/resultsByQuestionAndComplete?startkey=%22Participant%20Registration-es%3Atrue%3Az%22&endkey=%22Participant%20Registration-es%3Atrue%22&descending=true&include_docs=false';
     //$req_url = 'http://localhost:5984/coconut/_design/coconut/_view/resultsByQuestionAndCompleteWithCollateral?startkey=%22Participant%20Registration-es%3Atrue%3Az%22&endkey=%22Participant%20Registration-es%3Atrue%22&descending=true&include_docs=false';

    // prepare the request options
    $req_options = array(
        'method' => 'GET',
        'timeout' => 300.0,
        'headers' => array(
            'Content-Type' => 'application/json'
        ));

    // query couchdb data
    $couch_response = drupal_http_request( $req_url, $req_options );


    // decode to json objects
    $rows = drupal_json_decode( $couch_response->data)['rows'];

    $size = sizeof($rows);
    $numRows = sizeof($rows);
    ajetllog_log("ajexportregs", "MESSAGE", "******Registration rows fetched:".$size);


    $i = 0;
    $docProcessed = 0;
    $line = ajexportregs_writeHeader();
    array_push($linesAry, $line);

    $docIdsAry = array();
    $providerIds = array();

    foreach ( $rows as $one_row ){
        array_push($docIdsAry,$one_row['id']);
        $tempSize = sizeof($docIdsAry);
        $cnt = $docProcessed + $tempSize;

        if ( $i < $CHUNK_SIZE -1 && $cnt < $numRows -1  ) {
            $i++;
            continue;
        }

        // open all docs from this chunk
        $allDocs = openDocs($docIdsAry);
        $docProcessed += sizeof($allDocs);
        $docIdsAry = array();
        $i = 0;



        foreach ( $allDocs as $doc ) {
            // save provider id
            if(array_key_exists('provider_id', $doc['doc'])){
                if (!array_key_exists($doc['doc']['provider_id'], $providerIds))
                    $key = strval($doc['doc']['provider_id']);
                    $providerIds[$key] = $key;
            }

            // convert document to CSV line
            $line = ajexportregs_Doc2CSVLine($doc['doc']);

            // push to the final array
            array_push($linesAry, $line);

            //$result = ajexportregs_varDumpToString($doc['doc']);

            //ajetllog_error("ajexportregs", "MESSAGE0000", "doc=", $result, "");

        }


       // ajetllog_error("ajexportregs", "MESSAGE", "Document Processed", $docProcessed, "");

        //if ($docProcessed > 300)
        //  break;

    }

     // export all data
     ajexportregs_generateAllData($linesAry);

     // export data by provider
     ajexportregs_generateDataByProvider($providerIds, $linesAry);

    // clean
    ajexportregs_deleteModuleVariables();
    
    ajetllog_log("ajexportregs", "MESSAGE", "*****Registrations data successfully exported.");
 }catch(Exception $e){
     ajetllog_log("ajexportregs", "ERROR", $e->getMessage());

 }
}


/**
 * Export all data to CSV.
 *
 * @param $lineAry
 *
 */
function ajexportregs_generateAllData($linesAry){
    // convert array to string
    $data = implode("\r\n", $linesAry);

    // dump data to the file
    ajexportregs_generateFile(null,$data);

}


/**
 * Export all data to CSV.
 *
 * @param $lineAry
 *
 */
function ajexportregs_generateDataByProvider($providerIds, $linesAry){
    $lineAryByProvider = array();

    // push the header
    foreach ($providerIds as $pId) {
        $lineAryByProvider[$pId] = array();
        array_push($lineAryByProvider[$pId],$linesAry[0]);
    }



        // skip the header and start from the 2nd element
        for($i = 1; $i < sizeof($linesAry); $i++) {
            $lnAry = explode(',', $linesAry[$i]);

            // remove "" from provider id
            $id = trim($lnAry[1], '"');

            if ($id == "" || $id == null)
                continue;

            // push the line into the array
            if (array_key_exists($id, $lineAryByProvider)) {
                array_push($lineAryByProvider[$id], $linesAry[$i]);
            }

        }


        foreach($lineAryByProvider as $providerId=>$lines) {

            // convert array to string
            $data = implode("\r\n", $lines);

            // dump data to the file
            ajexportregs_generateFile($providerId, $data);
        }

}

/**
 *
 * @param $docIds
 */
function openDocs($docIds){
   $req_url = "http://localhost:5984/coconut/_all_docs?keys=[";
   $urlIds = "";
   $start = true;

  $size = sizeof($docIds);


   foreach($docIds as $id){
       if ($start) {
           $urlIds ='%22'.$id.'%22';
           $start = false;
       }else{
           $urlIds =$urlIds.',%22'.$id.'%22';
       }
   }

    $req_url = $req_url.$urlIds."]&include_docs=true";


    // prepare the request options
    $req_options = array(
        'method' => 'GET',
        'timeout' => 300.0,
        'headers' => array(
            'Content-Type' => 'application/json'
        ));

    // query couchdb data
    $couch_response = drupal_http_request( $req_url, $req_options );

    // decode to json objects
    $rows = drupal_json_decode( $couch_response->data)['rows'];

    $size = sizeof($rows);

   // ajetllog_log("ajexportregs", "MESSAGE", "******Rows fetched FROM CHUNK:".$size);

    return $rows;
}

function ajexportregs_varDumpToString($var) {
    ob_start();
    var_dump($var);
    $result = ob_get_clean();
    return $result;
}

/**
 * Opens the document by Id and returns the JSON object.
 *
 * @param $id
 */
function ajexportregs_OpenRegById($id){
    // TBD: changed hard coded localhost link
    $req_url = 'http://localhost:5984/coconut/'.$id;

    $req_options = array(
        'method' => 'GET',
        'headers' => array(
            'Content-Type' => 'application/json'
        ));

    $couch_response = drupal_http_request( $req_url, $req_options );
    $doc = drupal_json_decode( $couch_response->data);

    return $doc;

}

/**
 * Writes header line for the CSV file.
 */
function ajexportregs_writeHeader(){
    $regKeys = variable_get("ajRegKeys");
    $line = "";

    // write header
    $start = true;
    foreach ($regKeys as $k=>$key) {
        // add BOM to UTF8
        //$key = chr(239) . chr(187) . chr(191) . $key;
        if ($start){
            $start = false;
            $line = $key;
        }else {
            $line = $line . "," . $key;
        }
    }

    $utf8_with_bom = chr(239) . chr(187) . chr(191) .$line;
    return $utf8_with_bom;
}


/**
 * Write document to csv line.
 *
 * @param $doc
 * @return string
 */
function ajexportregs_Doc2CSVLine($doc){
    $regKeys = variable_get("ajRegKeys");
    $line = "";


    $start = true;
    foreach ($regKeys as $k=>$key) {
        if (!array_key_exists($key, $doc)) {
            $line = $line . ',';
            continue;
        }

        // clean '"" that brake the csv line
        $val = str_replace ( '"', '' , $doc[$key]);
        if ($start){
                $start = false;
                $line = $val;
        }else {
                $line = $line . ',"' . $val.'"';
        }

    }

    $utf8_with_bom = chr(239) . chr(187) . chr(191) . $line;
    return $utf8_with_bom;
}





/**
 * Generates the CSV file. The location for the file is
 *
 *      apps\drupal\htdocs\sites\default\files\ajexport
 *
 * param array() $lines
 *      int $save_mode
 *    File save mode from drupal core, ex FILE_EXISTS_REPLACE
 */
function ajexportregs_generateFile($pId, $data, $save_mode = FILE_EXISTS_REPLACE) {
    try{
        if ($pId != null)
          $uri  =  'public://ajexport/AJRegistrations_'.$pId.'.csv';
        else
          $uri  =  'public://ajexport/AJRegistrations.csv';

        //Need to remove the filename from the uri
        $uri_target = file_uri_target($uri);
        $uri_scheme = file_uri_scheme($uri);
        $uri_path_info = pathinfo($uri_target);

        $directory = file_stream_wrapper_uri_normalize($uri_scheme . "://" . $uri_path_info['dirname']);

        if(file_prepare_directory($directory, FILE_CREATE_DIRECTORY)) {
            $path = file_stream_wrapper_uri_normalize($uri);
            $new_file = file_save_data($data, $path, $save_mode);
        } else {
            ajetllog_log("ajexportregs", "ERROR", "ajexportregs Could not create directory");
        }
    }catch(Exception $e){
        ajetllog_log("ajexportregs", "ERROR", $e->getMessage());
    }
}


/**
 *
 * Use variable_set() to set module global variables.
 *
 *
 */
function ajexportregs_setModuleVariables()
{
    try{
      // retrieve aj-registration table columns
        $regKeys = array("uuid","provider_id","provider_name","createdAt","lastModifiedAt","user_name","Fecha","Apellido","Apodo","Año","Sexo","BarrioComunidad","Calleynumero","Casa","Celular","Completado","Direccióndecorreoelectrónico","Día","Mes",
            "Municipio","Nombre","Nombredepersonadecontacto","NombredeusuariodeFacebook","Parentescoopersonarelacionada","Provincia","Teléfono","Estecolateralparticipante","Tieneunadireccióndecorreoelectrónico","TieneunnombredeusuariodeFacebook",
            "Tieneunnumerocelular","Tieneunnumerodetelefonoenlacasa");
        
      // set the columns as variable
      variable_set("ajRegKeys", $regKeys);
    }catch(Exception $e){
        ajetllog_log("ajexportregs", "ERROR", $e->getMessage());

    }
}
/**
 * Implement hook_enable()
 */
function ajexportregs_enable() {

}

/**
 * Delete module variables.
 */
function ajexportregs_deleteModuleVariables(){
    variable_del("ajRegKeys");

}
