// Generated by CoffeeScript 1.9.2
(function(doc) {
  if (doc.question !== "Attendance List" && doc.question !== "MARP-es" && doc.question !== "Exit Survey-es") {
    return emit(doc.uuid, null);
  }
});

//# sourceMappingURL=map.js.map
