// Generated by CoffeeScript 1.6.3
(function(doc) {
  var community, family, hasRequiredFields, key, names, sexo, spacePattern;
  if (doc.collection === "result" && doc.Completado) {
    hasRequiredFields = (doc['Apellido'] != null) && (doc['Nombre'] != null) && (doc['BarrioComunidad'] != null) && (doc['Sexo'] != null);
    if (!hasRequiredFields) {
      return;
    }
    spacePattern = new RegExp(" ", "g");
    family = (doc['Apellido'] || '').toLowerCase();
    names = (doc['Nombre'] || '').toLowerCase();
    community = (doc['BarrioComunidad'] || '').toLowerCase();
    sexo = (doc['Sexo'] || '').toLowerCase();
    key = [family, names, community, sexo].join(":").replace(spacePattern, '');
    return emit(key, doc);
  }
});

//# sourceMappingURL=map.map
