// Generated by CoffeeScript 1.6.3
(function(doc) {
  var community, dobAno, dobDia, dobMes, family, hasRequiredFields, key, mes, municipality, names, sexo, spacePattern;
  if (doc.collection === "result" && doc.Completado) {
    hasRequiredFields = (doc['Apellido'] != null) && (doc['Nombre'] != null) && (doc['Municipio'] != null) && (doc['BarrioComunidad'] != null) && (doc['Sexo'] != null) && (doc['Día'] != null) && (doc['Mes'] != null) && (doc['Año'] != null);
    if (!hasRequiredFields) {
      return;
    }
    spacePattern = new RegExp(" ", "g");
    family = (doc['Apellido'] || '').toLowerCase();
    names = (doc['Nombre'] || '').toLowerCase();
    municipality = (doc['Municipio'] || '').toLowerCase();
    community = (doc['BarrioComunidad'] || '').toLowerCase();
    sexo = (doc['Sexo'] || '').toLowerCase();
    dobDia = (doc['Día'] || '').toLowerCase();
    if (dobDia.length < 2) {
      dobDia = "0" + dobDia;
    }
    dobMes = (doc['Mes'] || '').toLowerCase();
    mes = dobMes;
    switch (dobMes) {
      case "enero":
        mes = "01";
        break;
      case "febrero":
        mes = "02";
        break;
      case "marzo":
        mes = "03";
        break;
      case "abril":
        mes = "04";
        break;
      case "mayo":
        mes = "05";
        break;
      case "junio":
        mes = "06";
        break;
      case "julio":
        mes = "07";
        break;
      case "agosto":
        mes = "08";
        break;
      case "septiembre":
        mes = "09";
        break;
      case "octubre":
        mes = "10";
        break;
      case "noviembre":
        mes = "11";
        break;
      case "diciembre":
        mes = "12";
    }
    if (mes.length < 2) {
      mes = "0" + mes;
    }
    dobAno = (doc['Año'] || '').toLowerCase();
    key = [family, names, municipality, community, sexo, dobDia, mes, dobAno].join(":").replace(spacePattern, '');
    return emit(key, doc);
  }
});

/*
//@ sourceMappingURL=map.map
*/
