// Generated by CoffeeScript 1.6.3
(function(doc) {
  var community, dobAno, dobDia, dobMes, family, hasRequiredFields, key, municipality, names, sexo, spacePattern;
  if (doc.collection === "result" && doc.Completado) {
    hasRequiredFields = (doc['Apellido'] != null) && (doc['Nombre'] != null) && (doc['Municipio'] != null) && (doc['BarrioComunidad'] != null) && (doc['Sexo'] != null) && (doc['Día'] != null) && (doc['Mes'] != null) && (doc['Año'] != null);
    if (!hasRequiredFields) {
      return;
    }
    spacePattern = new RegExp(" ", "g");
    family = (doc['Apellido'] || '').toLowerCase();
    names = (doc['Nombre'] || '').toLowerCase();
    municipality = (doc['Municipio'] || '').toLowerCase();
    community = (doc['BarrioComunidad'] || '').toLowerCase();
    sexo = (doc['Sexo'] || '').toLowerCase();
    dobDia = (doc['Día'] || '').toLowerCase();
    dobMes = (doc['Mes'] || '').toLowerCase();
    dobAno = (doc['Año'] || '').toLowerCase();
    key = [family, names, municipality, community, sexo, dobDia, dobMes, dobAno].join(":").replace(spacePattern, '');
    return emit(key, doc);
  }
});

/*
//@ sourceMappingURL=map.map
*/
