// Generated by CoffeeScript 1.6.3
(function(doc) {
  if (doc.question === "Attendance List" && doc.hasOwnProperty('activity_id')) {
    return emit(doc.activity_id, doc);
  }
});

/*
//@ sourceMappingURL=map.map
*/
