CREATE TABLE `bitnami_drupal7`.`aj_labor` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The primary key identifier.',
  `provider_id` varchar(10) DEFAULT '' COMMENT 'Provider id.',
  `user_name` varchar(255) DEFAULT '' COMMENT 'User name who entered the data.',
  `uuid` varchar(12) NOT NULL DEFAULT '' COMMENT 'Universal unique id.',
  `created` datetime NOT NULL COMMENT 'The Unix timestamp when the record was created.',
  `changed` datetime DEFAULT NULL COMMENT 'The Unix timestamp when the record was updated.',
  `1_HasparticipadoenalguncursodelproyectoAlerta` varchar(2) DEFAULT '' COMMENT '1_HasparticipadoenalguncursodelproyectoAlerta.',
  `2_Hasparticipadoenalguntallerocursodelproyecto` varchar(2) DEFAULT '' COMMENT '2_Hasparticipadoenalguntallerocursodelproyecto.',
  `3_Hasparticipadoenalguntallerocursodelproyecto` varchar(2) DEFAULT '' COMMENT '3_Hasparticipadoenalguntallerocursodelproyecto.',
  `4_Actualmentetienesuntrabajoenel` varchar(2) DEFAULT '' COMMENT '4_Actualmentetienesuntrabajoenel.',
  `4_1Quehacesenesetrabajo` varchar(20) DEFAULT '' COMMENT '4_1Quehacesenesetrabajo.',
  `5_Cuantotiempotienesenestetrabajo` varchar(20) DEFAULT '' COMMENT '5_Cuantotiempotienesenestetrabajo.',
  `6_Estetrabajoes` varchar(10) DEFAULT '' COMMENT '6_Estetrabajoes.',
  `6_Otrofavorespecificar` varchar(20) DEFAULT '' COMMENT '6_Otrofavorespecificar.',
  `6_1Bajocualcondicion` varchar(12) DEFAULT '' COMMENT '6_1Bajocualcondicion.',
  `6_1Otrofavorespecificar` varchar(20) DEFAULT '' COMMENT '6_1Otrofavorespecificar.',
  `7_Cuantoganasenunasemana` varchar(20) DEFAULT '' COMMENT '7_Cuantoganasenunasemana.',
  `8_Cuandoiniciasteelcursotecnicoyaestabas` varchar(2) DEFAULT '' COMMENT '8_Cuandoiniciasteelcursotecnicoyaestabas.',
  `8_1Considerasquetutrabajoactual` varchar(2) DEFAULT '' COMMENT '8_1Considerasquetutrabajoactual.',
  `9_Enlosultimos12meseshashecho` varchar(2) DEFAULT '' COMMENT '9_Enlosultimos12meseshashecho.',
  `9_1Quehaciasenesetrabajo` varchar(20) DEFAULT '' COMMENT '9_1Quehaciasenesetrabajo.',
  `10_Cuantotiempodurasteenestetrabajo` varchar(20) DEFAULT '' COMMENT '10_Cuantotiempodurasteenestetrabajo.',
  `11_Esetrabajoera` varchar(10) DEFAULT '' COMMENT '11_Esetrabajoera.',
  `11_Otrofavorespecificar` varchar(20) DEFAULT '' COMMENT '11_Otrofavorespecificar.',
  `11_1Bajocualcondicion` varchar(12) DEFAULT '' COMMENT '11_1Bajocualcondicion.',
  `11_1Otrofavorespecificar` varchar(20) DEFAULT '' COMMENT '11_1Otrofavorespecificar.',
  `12_Cuantoganabasenunasemana` varchar(20) DEFAULT '' COMMENT '12_Cuantoganabasenunasemana.',
  `13_Hasrecibidounprestamoatravesdelproyecto` varchar(2) DEFAULT '' COMMENT '13_Hasrecibidounprestamoatravesdelproyecto.',
  `14_Tienesunnegociopropio` varchar(2) DEFAULT '' COMMENT '14_Tienesunnegociopropio.',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `ajlabor_created` (`created`),
  KEY `ajlabor_uuid` (`uuid`),
  KEY `ajlabor_provider_id` (`provider_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='AJ labor form entered .';
