<?php
/**
* @file
* A block module that displays Coconut surveys.
*/

/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/
error_reporting(E_ALL);
ini_set("display_errors", 1);

function coconut_help( $path, $arg )
{
  if ( $path == "admin/help#coconut" )
  {
    return '<p>' . t( "Displays Coconut surveys." ) . '</p>';
  }
}




/**
* Implements hook_block_info().
*/
function coconut_block_info() {
  global $base_url;
  $blocks = array();


  // request to couch to get documents of type question
  $req_url = "$base_url:5984/coconut/_design/coconut/_view/byCollection?key=\"question\"";
  $req_options = array(
    'headers' => array(
      'Content-Type' => 'application/json'
  ));

  $couch_response = drupal_http_request( $req_url, $req_options );

  $rows = drupal_json_decode( $couch_response->data )['rows'];

  foreach ( $rows as $one_row )
  {
    $blocks[$one_row['id']] = array(
      'info' => "Coconut: {$one_row['id']}",
      'cache' => DRUPAL_CACHE_PER_ROLE
    );
  }

  return $blocks;
}



function coconut_block_view( $delta = '' )
{


  global $user, $base_url;
  $block = array();
  $path = current_path();
  $user_name = isset($user->name) ? $user->name : '';

// Get provider name and id
  $user_data = user_load($user->uid);
  $provider = $user_data->field_user_provider;

  if (isset($provider['und']))
    $provider_id = $provider['und'][0]['target_id'];
  
  // load provider entity
  if (isset($provider_id)){
  	$entity = entity_load_single('provider', $provider_id);
  	$provider_name = $entity->{'title'};

       // Put it all together
       $a_user_parameters = array(
           "user_name={$user_name}",    
           "provider_name={$provider_name}",
           "provider_id={$provider_id}",	
       );
  }else{
       $a_user_parameters = array("user_name={$user_name}");
  }

   $s_user_parameters = join("&", $a_user_parameters);


   /* Send request to couch
   * ask for docs of type questions
   */
  $req_url = "$base_url:5984/coconut/_design/coconut/_view/byCollection?key=\"question\"";
  $req_options = array(
    'headers' => array(
      'Content-Type' => 'application/json'
    )
  );
  $couch_response = drupal_http_request( $req_url, $req_options );
  
  /*
   * Parse response
   */

  $surveys = array();
  $rows = drupal_json_decode( $couch_response->data )['rows'];
  foreach ( $rows as $one_row ) array_push( $surveys, $one_row['id'] );


       $html = "<script>window.resizeIFrame = function (height) { document.getElementById('coconut_iframe').style.height = '' + parseInt(height) + 'px'; }window.resizerWait = 1000;window.resizerCheck = function() { 
  jQuery.ajax({
    'url':'$base_url:5984/coconut/$delta-height', 
    dataType: 'jsonp', 
    success: function( data ) { window.resizerWait = 0; window.resizeIFrame(data.height); }, 
    complete: function() { if (window.resizerWait !== 0) { window.resizerWait *= 1.5; setTimeout(window.resizerCheck, window.resizerWait);}   }
  }); 
};
</script>";


  /*
   * Build block
   */
  if ( in_array( $delta, $surveys ) && $delta != 'Registration Report' && $delta!= 'Survey Report')
  {
    $block['subject'] = t( $delta );
    if ( user_access('access content') ){
      $html = $html."<iframe id='coconut_iframe' width='100%' height='600px' src='$base_url:5984/coconut/_design/coconut/index.html#new/result/$delta/{$s_user_parameters}'></iframe>";
      $block['content'] = $html;
    }
  } else if($delta == 'Registration Report'){
    
    if ( user_access('access content') ){
      $html = $html."<iframe id='coconut_iframe' width='100%' height='600px' src='$base_url:5984/coconut/_design/coconut/index.html#reports/Participant Registration-es/startDate=2013-07-31/endDate=2014-08-30/provider_id=$provider_id/user_name=$user_name'></iframe>";
      $block['content'] = $html;
    }
} else if($delta == 'Survey Report'){
    
    if ( user_access('access content') ){
      $html = $html."<iframe id='coconut_iframe' width='100%' height='600px' src='$base_url:5984/coconut/_design/coconut/index.html#reports/Participant Survey-es/startDate=2013-07-31/endDate=2014-08-30/provider_id=$provider_id/user_name=$user_name'></iframe>";
      $block['content'] = $html;
    }
}else{
    $block = array(
      'subject' => $delta,
      'content' => '404 - This survey no longer exists.'
      );
  }
  return $block;

}



