<?php
/**
* @file
* A block module that displays Coconut surveys.
*/

/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/
function coconut_help( $path, $arg )
{
  if ( $path == "admin/help#coconut" )
  {
    return '<p>' . t( "Displays Coconut surveys." ) . '</p>';
  }
}


/**
 * Implements hook_block_info().
 *
 * Basically this just queries CouchDB to see what 'question' documents it has.
 */
function coconut_block_info() {

  $blocks = array();

  // request to couch to get documents of type question
  $req_url = "http://localhost:5984/coconut/_design/coconut/_view/byCollection?key=\"question\"";
  $req_options = array(
    'headers' => array(
      'Content-Type' => 'application/json'
  ));

  $couch_response = drupal_http_request( $req_url, $req_options );

  $rows = drupal_json_decode( $couch_response->data )['rows'];

  foreach ( $rows as $one_row )
  {
    $blocks[$one_row['id']] = array(
      'info' => "Coconut: {$one_row['id']}",
      'cache' => DRUPAL_CACHE_PER_ROLE
    );
  }

  return $blocks;

} // END of coconut_block_info


/*
 * 
 */

function coconut_block_view( $delta = '' )
{

  global $user, $base_url;
  $block = array();
  $path = current_path();


  /*
   * Get some data to throw in
   */

  // User name, easy
  $user_name = isset($user->name) ? $user->name : '';

  // Get provider taxonomy term's ID
  $user_data = user_load($user->uid);
  $provider = $user_data->field_provider;
  $provider_tid = $provider['und'][0]['tid'];

  // get the name of that taxonomy term, just for human readability
  $taxonomy_term = taxonomy_term_load($provider_tid);
  $taxonomy_name = $taxonomy_term->name;

   // Put it all together
  $a_user_parameters = array(
    "user_name={$user_name}",
    "provider_tid={$provider_tid}",
    "provider_name={$taxonomy_name}"
  );
  $s_user_parameters = join("&", $a_user_parameters);


  /*
   * Send request to couch
   * ask for docs of type questions
   */
  $req_url = "http://localhost:5984/coconut/_design/coconut/_view/byCollection?key=\"question\"";
  $req_options = array(
    'headers' => array(
      'Content-Type' => 'application/json'
    )
  );
  $couch_response = drupal_http_request( $req_url, $req_options );

  /*
   * Parse response
   */

  $surveys = array();
  $rows = drupal_json_decode( $couch_response->data )['rows'];
  foreach ( $rows as $one_row ) array_push( $surveys, $one_row['id'] );


  /*
   * Build block
   */
  if ( in_array( $delta, $surveys ) )
  {
    $block['subject'] = t( $delta );
    if ( user_access('access content') )
    {
      $html = "
<iframe id='coconut_iframe' width='100%' height='600px' src='$base_url:5984/coconut/_design/coconut/index.html#new/result/$delta/{$s_user_parameters}'></iframe>";
      $block['content'] = $html;
    }
  } else
  {
    $block = array(
      'subject' => $delta,
      'content' => '404 - This survey no longer exists.'
      );
  }

  return $block;

} // END of coconut_block_view