// Generated by CoffeeScript 1.6.3
(function(doc) {
  if (doc.question === "Participant Registration-es" && doc.Provincia === "DISTRITO NACIONAL" && ((doc.user_name == null) || doc.user_name === "undefined")) {
    return emit(doc.id, null);
  }
});
