// Generated by CoffeeScript 1.6.3
(function($) {
  $.fn.getRandom = function() {
    return this[Math.floor(Math.random() * this.length)];
  };
  $.fn.scrollTo = function(speed, callback) {
    var e;
    if (speed == null) {
      speed = 500;
    }
    try {
      $('html, body').animate({
        scrollTop: $(this).offset().top + 'px'
      }, speed, null, callback);
    } catch (_error) {
      e = _error;
      console.log("error", e);
      console.log("Scroll error with 'this'", this);
    }
    return this;
  };
  return $.fn.safeVal = function() {
    if (this.is(":visible")) {
      return (this.val() || '').trim();
    } else {
      return null;
    }
  };
})($);

/*
//@ sourceMappingURL=jquery.custom.map
*/
