// Generated by CoffeeScript 1.6.3
(function(doc) {
  if (doc.Completado === "true") {
    if (doc.question === "Participant Survey-es") {
      return emit(doc.uuid + "$" + "true$" + doc.lastModifiedAt, null);
    }
  } else {
    if (doc.question === "Participant Survey-es") {
      return emit(doc.uuid + "$" + "false$" + doc.lastModifiedAt, null);
    }
  }
});

/*
//@ sourceMappingURL=map.map
*/
