// Generated by CoffeeScript 1.6.3
(function(doc) {
  if (doc.uuid === "PB4GP475N" || doc.uuid === "8CCWXHQC*" || doc.uuid === "S2F6S85FN" || doc.uuid === "B65R6WFAG" || doc.uuid === "G9H2CYC0U" || doc.uuid === "E99BWNEKW" || doc.uuid === "SE65AT5VM" || doc.uuid === "EVDH5XA4*" || doc.uuid === "6172JTSDS" || doc.uuid === "WH0XSQANP" || doc.uuid === "VQX2P1PR7" || doc.uuid === "EQAB5D7W=" || doc.uuid === "7CFHFPN6=" || doc.uuid === "7CFHFPN6=" || doc.uuid === "7CFHFPN6=" || doc.uuid === "5Y6Z9Z8HB" || doc.uuid === "08BY19GK5" || doc.uuid === "9T4W7VC8S" || doc.uuid === "P27MCP8B2" || doc.uuid === "NR4KHA42*" || doc.uuid === "K7MK9KA1T" || doc.uuid === "R93NN4D3G" || doc.uuid === "7P8EFBFG4" || doc.uuid === "3FANAJ88R" || doc.uuid === "DPGMMC56V" || doc.uuid === "KSCHEVR5S" || doc.uuid === "P2W760R3Z" || doc.uuid === "63SDZT1C4" || doc.uuid === "HW9M47010" || doc.uuid === "TQETZJVH7" || doc.uuid === "VCKMQK3NZ" || doc.uuid === "R3RGW7RY6" || doc.uuid === "9KBD4R4FE" || doc.uuid === "73M7GZSAC" || doc.uuid === "RD2TYY3KJ" || doc.uuid === "XSJCMQKKS" || doc.uuid === "YEC05DGMC") {
    return emit(doc.uuid, doc.id);
  }
});

/*
//@ sourceMappingURL=map.map
*/
