<?php

/**
 * @filesource
 * This is the hook_help implementation
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function ajlabor_help($path, $arg) {
	switch ($path) {
		case "admin/help#ajlabor":
			return '<p>' . t("Implementation of the Labor Survey Form") . '</p>';
			break;
	}
}

/**
 *Implements the hook_menu
 */
 function ajlabor_menu() {
	$items = array();

	$items['ajlabor'] = array(
		'title' => 'Labor Survey form',
		'description' => 'Form to collect data of a Labor Insertion participant',
		'page callback' => '_ajlabor_page',
    	'page arguments' => array('ajlabor_form'),
		'access arguments' => array('access ajlabor content'),
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
 }

 /**
  *  Page callback: Current users settings
  *  @see current_users_menu()
  */
function ajlabor_form($form, &$form_state) {

	$urlParams = drupal_get_query_parameters();
	$uuid = $urlParams['uuid'];

	$beneficiary = _ajlabor_getBeneficiaryInfo($uuid);
	$beneficiaryDetails = $beneficiary['nombre'].' '.$beneficiary['apellido'].' ('.$uuid.')';

	if (_ajlabor_alreadyExist($uuid)) {
		drupal_set_message(t('Ya existe una Encuesta de Inserción Laboral disponible para <b>'.$beneficiaryDetails.'</b>'), 'warning');
		 $form['actions']['cancel'] = array(
  		  '#markup' => l(t('Volver a Lista de Beneficiarios'), 'mis-beneficiarios'),
 		 );
		return $form;
	}

	$label = '<p>Estás creando una Encuesta de Inserción Laboral para <b>'.$beneficiaryDetails.'</b></p>';
	$form['welcome'] = array(
	  '#markup' => $label,
	);

// 	// Vertical tabs container
// 	$form['group_tabs'] = array(
// 		'#type'     => 'vertical_tabs',
// 		'#attached' => array('library' => array(array('field_group', 'vertical_tabs'))), // Converts fieldsets into tabs
// 	);

// 	// Tab 1
// 	$form['documentation'] = array(
//     	'#type'  => 'fieldset',
//     	'#title' => t('Documentación'),
//     	'#collapsible' => TRUE,
//     	'#collapsed' => FALSE,
//     	'#group' => 'group_tabs',
// 	);

// 	// Tab 2
// 	$form['education'] = array(
//     	'#type'  => 'fieldset',
//     	'#title' => t('Educación'),
//     	'#group' => 'group_tabs',
// 	);

// 	// Tab 3
// 	$form['labor'] = array(
//     	'#type'  => 'fieldset',
//     	'#title' => t('Laboral'),
//     	'#group' => 'group_tabs',
// 	);

// 	// Tab 4
// 	$form['programs'] = array(
//     	'#type'  => 'fieldset',
//     	'#title' => t('Programas'),
//     	'#group' => 'group_tabs',
// 	);

// 	// Tab 5
// 	$form['violence'] = array(
//     	'#type'  => 'fieldset',
//     	'#title' => t('Crimen y Violencia'),
//     	'#group' => 'group_tabs',
// 	);

// 	// Tab 6
// 	$form['sexual'] = array(
//     	'#type'  => 'fieldset',
//     	'#title' => t('Educación Sexual'),
//     	'#group' => 'group_tabs',
// 	);

// 	// Tab 7
// 	$form['exit'] = array(
//     	'#type'  => 'fieldset',
//     	'#title' => t('Cierre'),
//     	'#group' => 'group_tabs',
// 	);

	$YesNoOptions = array(
		1 => t('Sí'),
		2 => t('No'),
	);

	$form['1'] = array(
		'#type' => 'select',
		'#title' => t('1. ¿Has participado en algún curso del proyecto Alerta Joven en el que te enseñaron algo que te puede servir para trabajar?'),
		'#options' => drupal_map_assoc($YesNoOptions),
		'#required' => TRUE,
	);
	
	$form['2'] = array(
			'#type' => 'select',
			'#title' => t('2. ¿Has participado en algún taller o curso del proyecto Alerta Joven para tener tu propio negocio?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#required' => TRUE,
	);
	
	$form['3'] = array(
			'#type' => 'select',
			'#title' => t('3. ¿Has participado en algún taller o curso del proyecto Alerta Joven para tener un préstamo y hacer tu propio negocio?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#required' => TRUE,
	);

	$form['4'] = array(
		'#type' => 'select',
		'#title' => t('4. ¿Actualmente tienes un trabajo en el que te paguen?'),
		'#options' => drupal_map_assoc($YesNoOptions),
		'#empty_option' => t('- Select -'),
		'#required' => FALSE,
		 '#states' => array(
      		'visible' => array(
        		array('select[name="1"]' => array('value' => 'Sí')),
      			array('select[name="2"]' => array('value' => 'Sí')),
      			array('select[name="3"]' => array('value' => 'Sí')),
      		),
    	),
	);
	
	$form['4_1'] = array(
			'#type' => 'textfield',
			'#title' => t('4.1 ¿Qué haces en ese trabajo?'),
			'#size' => 30,
			'#maxlength' => 30,
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="4"]' => array('value' => 'Sí')
					),
			),
	);
	
	$_5Options = array(
			1 => t('Menos de una semana'),
			2 => t('1 a 3 semanas'),
			3 => t('1 a 3 meses'),
			4 => t('Más de 3 meses'),
	);
	
	$form['5'] = array(
			'#type' => 'select',
			'#title' => t('5. ¿Cuánto tiempo tienes en este trabajo?'),
			'#options' => drupal_map_assoc($_5Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="4"]' => array('value' => 'Sí')
					),
			),
	);
	
	$_6Options = array(
			1 => t('Fijo'),
			2 => t('Temporal'),
			3 => t('Pasantía'),
			4 => t('Otro'),
	);
	
	$form['6'] = array(
			'#type' => 'select',
			'#title' => t('6. ¿Este trabajo es...?'),
			'#options' => drupal_map_assoc($_6Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="4"]' => array('value' => 'Sí')
					),
			),
	);

	$form['6Otro'] = array(
		'#type' => 'textfield',
		'#title' => t('6.Otro (favor especificar):'),
		'#required' => FALSE,
		'#maxlength' => 50,
		'#states' => array(
      		'visible' => array(
        			array('select[name="1"]' => array('value' => 'Sí')),
					array('select[name="2"]' => array('value' => 'Sí')),
					array('select[name="3"]' => array('value' => 'Sí')),
      				'select[name="4"]' => array('value' => 'Sí'),
					'select[name="6"]' => array('value' => 'Otro'),
      			),
    		),
	);
	
	$_6_1Options = array(
			1 => t('Con contrato'),
			2 => t('Sin contrato'),
			3 => t('Otro'),
	);
	
	$form['6_1'] = array(
			'#type' => 'select',
			'#title' => t('6.1 ¿Bajo cuál condición?'),
			'#options' => drupal_map_assoc($_6_1Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="4"]' => array('value' => 'Sí'),
					),
			),
	);
	
	$form['6_1Otro'] = array(
			'#type' => 'textfield',
			'#title' => t('6.Otro (favor especificar):'),
			'#required' => FALSE,
			'#maxlength' => 50,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="4"]' => array('value' => 'Sí'),
							'select[name="7"]' => array('value' => 'Otro'),
					),
			),
	);
	
	$_7Options = array(
			1 => t('Menos de 1,000'),
			2 => t('De 1,001 - 3,000'),
			3 => t('Más de 3,000'),
	);
	
	$form['7'] = array(
			'#type' => 'select',
			'#title' => t('7. ¿Cuánto ganas en una semana?'),
			'#options' => drupal_map_assoc($_7Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="4"]' => array('value' => 'Sí'),
					),
			),
	);
	
	$form['8'] = array(
			'#type' => 'select',
			'#title' => t('8. Cuando iniciaste el curso técnico ¿ya estabas en algún trabajo en el que te pagaban?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="4"]' => array('value' => 'Sí'),
					),
			),
	);
	
	$form['8_1'] = array(
			'#type' => 'select',
			'#title' => t('8.1 ¿Consideras que tu trabajo actual es mejor que el anterior?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="4"]' => array('value' => 'Sí'),
							'select[name="8"]' => array('value' => 'Sí'),
					),
			),
	);
	
	$form['9'] = array(
			'#type' => 'select',
			'#title' => t('9. ¿En los últimos 12 meses has hecho algún trabajo en el que te hayan pagado?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
					),
			),
	);
	
	$form['9_1'] = array(
			'#type' => 'select',
			'#title' => t('9.1 ¿Qué hacías en ese trabajo?'),
			'#size' => 30,
			'#maxlength' => 30,
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="10"]' => array('value' => 'Sí')
					),
			),
	);
	
	$form['10'] = array(
			'#type' => 'select',
			'#title' => t('10. ¿Cuánto tiempo duraste en este trabajo?'),
			'#options' => drupal_map_assoc($_5Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="10"]' => array('value' => 'Sí'),
					),
			),
	);
	
	$form['11'] = array(
			'#type' => 'select',
			'#title' => t('11. ¿Ese trabajo era...?'),
			'#options' => drupal_map_assoc($_6Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="10"]' => array('value' => 'Sí'),
					),
			),
	);
	
	$form['11Otro'] = array(
			'#type' => 'textfield',
			'#title' => t('11.Otro (favor especificar):'),
			'#required' => FALSE,
			'#maxlength' => 50,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="10"]' => array('value' => 'Sí'),
							'select[name="12"]' => array('value' => 'Otro'),
					),
			),
	);
	
	$form['11_1'] = array(
			'#type' => 'select',
			'#title' => t('11.1 ¿Bajo cuál condición?'),
			'#options' => drupal_map_assoc($_6_1Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="10"]' => array('value' => 'Sí'),
					),
			),
	);
	
	$form['11_1Otro'] = array(
			'#type' => 'textfield',
			'#title' => t('11.1 Otro (favor especificar):'),
			'#required' => FALSE,
			'#maxlength' => 50,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="10"]' => array('value' => 'Sí'),
							'select[name="12_1"]' => array('value' => 'Otro'),
					),
			),
	);
	
	$form['12'] = array(
			'#type' => 'select',
			'#title' => t('12. ¿Cuánto ganabas en una semana?'),
			'#options' => drupal_map_assoc($_7Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
							'select[name="10"]' => array('value' => 'Sí'),
					),
			),
	);
	
	$form['13'] = array(
			'#type' => 'select',
			'#title' => t('13. ¿Has recibido un préstamo a través del proyecto Alerta Joven para montar tu negocio?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
					),
			),
	);
	
	$form['14'] = array(
			'#type' => 'select',
			'#title' => t('14. ¿Tienes un negocio propio actualmente?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
					),
			),
	);
	
	$form['actions'] = array('#type' => 'actions');

	$form['actions']['cancel'] = array(
		'#type' => 'submit',
		'#prefix' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<div style="display: inline-block; width: 200px;" class = "remove"><br>',
		'#sufix' => '</div> <br>',
		'#value' => t('Cancelar'),
		'#limit_validation_errors' => array(),
		'#submit' => array('ajregistration_form_submit'),
		'#weight' => 100,
	);

	$form['actions']['submit'] = array(
		'#type' => 'submit',
		'#prefix' => '',
		'#sufix' => '',
		'#value' => t('Guardar'),
		'#weight' => 100,
	);

	return $form;
}

/**
 * This is the hook implementation for _form_submit
 * @param unknown $form
 * @param unknown $form_state
 */
function ajlabor_form_submit($form, &$form_state) {

	if ( $form_state['clicked_button']['#value'] === 'Cancelar' ) {
		drupal_set_message('Formulario descartado', 'warning');
		$form_state['redirect'] = 'mis-beneficiarios';
		return;
	}

	$urlParams = drupal_get_query_parameters();
	$uuid = $urlParams['uuid'];
	$provider_id = $urlParams['provider_id'];

	$beneficiary = _ajlabor_getBeneficiaryInfo($uuid);
	$beneficiaryDetails = $beneficiary['nombre'].' '.$beneficiary['apellido'].' ('.$uuid.')';

//  	$_22 = $form_state['values']['22'];
//     $_22_date = $_22['year'].'-'. (strlen($_22['month']) === 1? '0'.$_22['month']:$_22['month']).'-'.(strlen($_22['day']) === 1? '0'.$_22['day']:$_22['day']);

// 	_ajlabor_insert_data(
// 			$form_state['values']['9'],
// 			$form_state['values']['9A'],
// 			$form_state['values']['9AOtro'],
// 			$form_state['values']['10'],
// 			$form_state['values']['11'],
// 			$form_state['values']['11A'],
// 			$form_state['values']['11B_1'],
// 			$form_state['values']['12'],
// 			$form_state['values']['12A'],
// 			$form_state['values']['13'],
// 			$form_state['values']['13A'],
// 			$form_state['values']['13B'],
// 			$form_state['values']['14A'],
// 			$form_state['values']['14B'],
// 			$form_state['values']['15A'],
// 			$form_state['values']['15B'],
// 			$form_state['values']['15C'],
// 			$form_state['values']['15D'],
// 			$form_state['values']['16'],
// 			$form_state['values']['17'],
// 			$form_state['values']['18'],
// 			$form_state['values']['19'],
// 			$form_state['values']['19Otro'],
// 			$form_state['values']['20'],
// 			$form_state['values']['21'],
// 			$_22_date,
// 			$form_state['values']['23'],
// 			$form_state['values']['23Otro'],
// 			$form_state['values']['24'],
// 			$uuid,
// 			$provider_id);

// 	drupal_set_message('La encuesta de inserción laboral ha sido guardado satisfactoriamente para <b>'.$beneficiaryDetails.'</b>!');

// 	$form_state['redirect'] = 'mis-beneficiarios';

}

/**
 *	Implements validation from the Form API.
 *
 * @param $form
 *   A structured array containing the elements and properties of the form.
 * @param $form_state
 *   An array that stores information about the form's current state
 *   during processing.
 */
 function ajlabor_form_validate($form, &$form_state) {

 	if (!isset($form['1'])) {
 		return;
 	}

 	$_1 = $form_state['values']['1'];
    $_2 = $form_state['values']['2'];
    $_3 = $form_state['values']['3'];
 	$_4 = $form_state['values']['4'];
    $_4_1 = $form_state['values']['4_1'];
    $_5 = $form_state['values']['5'];
 	$_6 = $form_state['values']['6'];
 	$_6Otro = $form_state['values']['6Otro'];
    $_6_1 = $form_state['values']['6_1'];
 	$_6_1Otro = $form_state['values']['6_1Otro'];
    $_7 = $form_state['values']['7'];
//     $_13A_date = $_13A['year'].'-'. (strlen($_13A['month']) === 1? '0'.$_13A['month']:$_13A['month']).'-'.(strlen($_13A['day']) === 1? '0'.$_13A['day']:$_13A['day']);
    $_8 = $form_state['values']['8'];
 	$_8_1 = $form_state['values']['8_1'];
 	$_9 = $form_state['values']['9'];
 	$_9_1 = $form_state['values']['9_1'];
 	$_10 = $form_state['values']['10'];
 	$_11 = $form_state['values']['11'];
 	$_11Otro = $form_state['values']['11Otro'];
 	$_11_1 = $form_state['values']['11_1'];
 	$_12 = $form_state['values']['12'];
 	$_19Otro = $form_state['values']['19Otro'];
 	$_22 = $form_state['values']['22'];
    $_22_date = $_22['year'].'-'. (strlen($_22['month']) === 1? '0'.$_22['month']:$_22['month']).'-'.(strlen($_22['day']) === 1? '0'.$_22['day']:$_22['day']);
 	$_23 = $form_state['values']['23'];
 	$_23Otro = $form_state['values']['23Otro'];

	$now = date('Y-m-d', time());

// 	watchdog('claudia', $_22_date);
// 	var_dump($_22_date);
// 	drupal_set_message(t('22. Fecha de Revisión: Esta fecha no es válida'));
// 	form_error($form, t('heyyyyy'));

	// QUESTION 4 to 14 --------------------------------------------------------------
	if($_1 === 'Sí' || $_2 === 'Sí' || $_3 === 'Sí') {
	 	if (empty($_4)) {
			form_error($form['4'], t('4. ¿Actualmente tienes un trabajo en el que te paguen?: Campo requerido'));
		} 
		if (empty($_5)) {
			form_error($form['5'], t('5. ¿Cuánto tiempo tienes en este trabajo?: Campo requerido'));
		}
		if (empty($_6)) {
			form_error($form['6'], t('6. ¿Este trabajo es...?: Campo requerido'));
		}
		if (empty($_7)) {
			form_error($form['7'], t('7. ¿Cuánto ganas en una semana?: Campo requerido'));
		}
		if (empty($_8)) {
			form_error($form['8'], t('8. Cuando iniciaste el curso técnico ¿ya estabas en algún trabajo en el que te pagaban?: Campo requerido'));
		}
		if (empty($_9)) {
			form_error($form['9'], t('9. ¿En los últimos 12 meses has hecho algún trabajo en el que te hayan pagado?: Campo requerido'));
		}
		if (empty($_10)) {
			form_error($form['10'], t('10. ¿Cuánto tiempo duraste en este trabajo?: Campo requerido'));
		}
		if (empty($_11)) {
			form_error($form['11'], t('11. ¿Ese trabajo era...?: Campo requerido'));
		}
		if (empty($_12)) {
			form_error($form['12'], t('12. ¿Cuánto ganabas en una semana?: Campo requerido'));
		}
		if (empty($_13)) {
			form_error($form['13'], t('13. ¿Has recibido un préstamo a través del proyecto Alerta Joven para montar tu negocio?: Campo requerido'));
		}
		if (empty($_14)) {
			form_error($form['14'], t('14. ¿Tienes un negocio propio actualmente?: Campo requerido'));
		}
	}

	// QUESTION 4_1 --------------------------------------------------------------
	if ($_4 === 'Sí') {
		if (empty($_4_1)) {
			form_error($form['4_1'], t('4.1 ¿Qué haces en ese trabajo?: Campo requerido'));
		}
	}

	// QUESTION 6_1 -------------------------------------------------------------------------------------
	if ($_6 === 'Sí') {
		if (empty($_12A)) {
			form_error($form['labor']['12A'], t('12A. Si la respuesta es afirmativa, ¿cuáles cursos?: Campo requerido'));
		}
	}

	// QUESTION 13A and 13B -------------------------------------------------------------------------------------
	if ($_13 === 'Sí') {
		// Check if the date is empty
 		if (empty($_13A_date)) {
			form_error($form['labor']['13A'], t('13A. ¿Cuándo empezaste en este trabajo?: Estos campos son requeridos'));
		}
		// Check if date is no later than today
		if (is_string($_13A_date) && strncmp($_13A_date, $now, 10) > 0 ) {
			form_error($form['labor']['13A'], t('13A. ¿Cuándo empezaste en este trabajo?: Fecha no puede ser después del día de hoy'));
		}
 		// Check if the date is valid and has the right format
		if (is_string($_13A_date) && strtotime($_13A_date) === FALSE || ((int)$_13A['year']) < 1991) {
			form_error($form['labor']['13A'], t('13A. ¿Cuándo empezaste en este trabajo?: Fecha no válida'));
		}
		if (empty($_13B)) {
			form_error($form['labor']['13B'], t('13B. ¿Estás en un mejor trabajo o empleo que el anterior?: Campo requerido'));
		}
	}

	// QUESTION 15A, 15B, 15C, 15D -------------------------------------------------------------------------------------
	if (!empty($_15A) && !is_numeric($_15A)) {
		form_error($form['violence']['15A'], t('15A. ¿Cuántas veces has sido transportado por la policía?: Debe ser un valor numérico'));
	}
 	if (!empty($_15B) && !is_numeric($_15B)) {
		form_error($form['violence']['15B'], t('15B. ¿Cuántas veces has sido arrestado por la policía?:  Debe ser un valor numérico'));
	}
 	if (!empty($_15C) && !is_numeric($_15C)) {
		form_error($form['violence']['15C'], t('15C. ¿Cuántas veces has sido acusado de cometer algún delito en la fiscalía o policía?: Debe ser un valor numérico'));
	}
 	if (!empty($_15D) && !is_numeric($_15D)) {
		form_error($form['violence']['15D'], t('15D. ¿Cuántas veces has sido enviado a un centro de atención integral?: Debe ser un valor numérico'));
	}


	// QUESTION 18 and 19 and 19Otro -------------------------------------------------------------------------------------
	if ($_17 === 'Sí') {
		if (empty($_18)) {
			form_error($form['sexual']['18'], t('18. La última vez que tuviste relaciones sexuales, ¿tú o tu compañero/a utilizó condón?: Campo requerido'));
		}
		if (empty($_19)) {
			form_error($form['sexual']['19'], t('19. La última vez que tuviste relaciones sexuales, ¿cuál método usaste o tu compañero/a para prevenir el embarazo?: Campo requerido'));
		} else if ($_19 === 'Otro (favor especificar)') {
			if (empty($_19Otro)) {
				form_error($form['sexual']['19Otro'], t('19.Otro (favor especificar): Campo requerido'));
			}
		}
	}

	// QUESTION 22 --------------------------------------------------------------
 	// Check if the date is empty
 	if (empty($_22_date)) {
		form_error($form['exit']['22'], t('22. Fecha de Revisión: Estos campo son requeridos'));
	}
	// 	Check if date is no later than today
	if (is_string($_22_date) && strncmp($_22_date, $now, 10) > 0  ) {
		form_error($form['exit']['22'], t('22. Fecha de Revisión: Esta fecha no puede ser después del día de hoy'));
	}
 	// Check if the date is valid and has the right format
//  	watchdog('claduia', strlen($_22['month']) );
	if (is_string($_22_date) && strtotime($_22_date) === FALSE || ((int)$_22['year']) < 2012) {
		form_error($form['exit']['22'], t('22. Fecha de Revisión: Esta fecha no es válida'));
	}

	// QUESTION 23Otro --------------------------------------------------------------
	if ($_23 === 'Otro (favor especificar)') {
		if (empty($_23Otro)) {
				form_error($form['exit']['23Otro'], t('23.Otro (favor especificar): Campo requerido'));
		}
	}
 }


 /**
  * Implements the hook_permissions
  */
 function ajlabor_permission() {
	return array(
		'access ajlabor content' => array(
				'title' => t('Access content for ajlabor module'),
				'description' => t('Control the access for the Exit form'),
		)
	);
 }


 /**
  *  Callback function that generates content
  */
function _ajlabor_page() {
	return drupal_get_form('ajlabor_form');
}

/**
 * Script to insert the new form data
 */
function _ajlabor_insert_data(
			$_9,
			$_9A,
			$_9AOtro,
			$_10,
			$_11,
			$_11A,
			$_11B_1,
			$_12,
			$_12A,
			$_13,
			$_13A,
			$_13B,
			$_14A,
			$_14B,
			$_15A,
			$_15B,
			$_15C,
			$_15D,
			$_16,
			$_17,
			$_18,
			$_19,
			$_19Otro,
			$_20,
			$_21,
			$_22,
			$_23,
			$_23Otro,
			$_24,
			$uuid,
			$provider_id) {
	global $user;
	$currentDate = format_date(time(), 'custom', 'Y-m-d H:i:s');

	$tableFields =  array(
 		'createdAt' => $currentDate,
 		'lastModifiedAt' => $currentDate,
		'created' => $currentDate,
		'uuid' => $uuid,
		'provider_id' => $provider_id,
		'user_name' => $user->name,
		'9Conseguistetuactade' => $_9,
		'9APorQueNoTienesActaDeNacimiento' => $_9A,
		'9AOtro' => $_9AOtro,
		'10Tienescédula' => $_10,
		'11Estasactualmente' => $_11,
		'11AQuégradoestascursandoactualmente' => $_11A,
		'11B1Cuálnivel' => $_11B_1,
		'12Hascompletadoa' => $_12,
		'12ASilarespuestaesafirmativacuálescursos' => $_12A,
		'13Actualmentetienesuntrabajoenquetepaguen' => $_13,
		'13AMes' => $_13A['month'],
		'13AAño' => $_13A['year'],
		'13BEstásenunmejortrabajooempleoqueelanterior' => $_13B,
		'15ACuántasveceshassido' => $_15A,
		'15BCuántasveceshassido' => $_15B,
		'15CCuántasveceshassido' => $_15C,
		'15DCuántasveceshassidoenviado' => $_15D,
		'16Enquémedidatuvidaha' => $_16,
		'17Algunavezhastenidorelacionessexuales' => $_17,
		'18Laúltimavez' => $_18,
		'19Laúltimavez' => $_19,
		'19AOtro' => $_19Otro,
		'20Siquisierascompraruncondóncreesquepodríasencontrarlo' => $_20,
		'21Siquisierastenersexo' => $_21,
		'22FechadeRevisión' => $_22,
		'23EstatusdeSalida' => $_23,
		'23AOtro' => $_23Otro,
		'24Comentarios' => $_24,
	);

	$exit_entry = db_insert('aj_exit')
	->fields($tableFields);
	$exit_entry->execute();

	$tableFieldsPrograms = array(
		'created' => $currentDate,
		'uuid' => $uuid,
		'provider_id' => $provider_id,
		'answer' => 'Participado',
	);

	foreach ($_14A as $programParticipation) {
		if ($programParticipation !== 0) {
			$tableFieldsPrograms['program_id'] = $programParticipation;
			$exit_programs_entry = db_insert('aj_exit_programs')
			->fields($tableFieldsPrograms);
			$exit_programs_entry->execute();
		}
	}

	$tableFieldsPrograms['answer'] = 'Completado';
	foreach ($_14B as $programCompleted) {
		if ($programCompleted !== 0) {
			$tableFieldsPrograms['program_id'] = $programCompleted;
			$exit_programs_entry = db_insert('aj_exit_programs')
			->fields($tableFieldsPrograms);
			$exit_programs_entry->execute();
		}
	}
}


/**
 * Get the beneficiary info
 */
function _ajlabor_getBeneficiaryInfo($uuid) {

	$query = db_select('aj_registration', 'reg');
	$query->fields('reg', array('nombre'));
	$query->fields('reg', array('apellido'));
	$query->fields('reg', array('uuid'));
	$query->condition('uuid', $uuid);
	$query->orderBy('nombre', 'ASC');
	$query->range(0,1);

	$result = $query->execute();
	return $result->fetchAssoc();
}

/**
 * Checks if a given uuid already has an exit entry in the database
 */
function _ajlabor_alreadyExist($uuid) {

	$query = db_select('aj_exit', 'ajlabor');
	$query->fields('ajlabor', array('uuid'));
	$query->condition('uuid', $uuid);
	$query->range(0,1);

	$result = $query->execute();
	$entry =  $result->fetchAssoc();

	return !empty($entry);
}
