<?php

/**
 * @filesource
 * This is the hook_help implementation
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function ajlabor_help($path, $arg) {
	switch ($path) {
		case "admin/help#ajlabor":
			return '<p>' . t("Implementation of the Labor Survey Form") . '</p>';
			break;
	}
}

/**
 *Implements the hook_menu
 */
 function ajlabor_menu() {
	$items = array();

	$items['ajlabor'] = array(
		'title' => 'Labor Survey form',
		'description' => 'Form to collect data of a Labor Insertion participant',
		'page callback' => '_ajlabor_page',
    	'page arguments' => array('ajlabor_form'),
		'access arguments' => array('access ajlabor content'),
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
 }

 /**
  *  Page callback: Current users settings
  *  @see current_users_menu()
  */
function ajlabor_form($form, &$form_state) {

	$urlParams = drupal_get_query_parameters();
	$uuid = $urlParams['uuid'];

	$beneficiary = _ajlabor_getBeneficiaryInfo($uuid);
	$beneficiaryDetails = $beneficiary['nombre'].' '.$beneficiary['apellido'].' ('.$uuid.'). Su edad actual es '. $beneficiary['edad']. ' años';

	if (_ajlabor_alreadyExist($uuid)) {
		drupal_set_message(t('Ya existe una Encuesta de Inserción Laboral disponible para <b>'.$beneficiaryDetails.'</b>'), 'warning');
		 $form['actions']['cancel'] = array(
  		  '#markup' => l(t('Volver a Lista de Beneficiarios'), 'mis-beneficiarios'),
 		 );
		return $form;
	}

	$label = '<p>Estás creando una Encuesta de Inserción Laboral para <b>'.$beneficiaryDetails.'</b></p>';
	$form['welcome'] = array(
	  '#markup' => $label,
	);

	// 	// Tab 3
	$form['initial'] = array(
			'#type'  => 'fieldset',
			'#title' => t('Participación en el programa'),
			'#collapsible' => true,
			'#collapsed' => false,
	);
	
	// Tab 1
	$form['laboral'] = array(
    	'#type'  => 'fieldset',
    	'#title' => t('Condición Laboral'),
    	'#collapsible' => true,
    	'#collapsed' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
					),
					),
	);

// 	// Tab 2
	$form['credits'] = array(
    	'#type'  => 'fieldset',
    	'#title' => t('Obtención de Microcréditos'),
    	'#collapsible' => true,
    	'#collapsed' => false,
    	'#group' => 'group_tabs',
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
					),
					),
	);

	$YesNoOptions = array(
		1 => t('Sí'),
		2 => t('No'),
	);

	$form['initial']['1'] = array(
		'#type' => 'select',
		'#title' => t('1. ¿Has participado en algún curso del proyecto Alerta Joven en el que te enseñaron algo que te puede servir para trabajar?'),
		'#options' => drupal_map_assoc($YesNoOptions),
		'#required' => TRUE,
	);
	
	$form['initial']['2'] = array(
			'#type' => 'select',
			'#title' => t('2. ¿Has participado en algún taller o curso del proyecto Alerta Joven para tener tu propio negocio?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#required' => TRUE,
	);
	
	$form['initial']['3'] = array(
			'#type' => 'select',
			'#title' => t('3. ¿Has participado en algún taller o curso del proyecto Alerta Joven para tener un préstamo y hacer tu propio negocio?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#required' => TRUE,
	);

	$form['laboral']['4'] = array(
		'#type' => 'select',
		'#title' => t('4. ¿Actualmente tienes un trabajo en el que te paguen?'),
		'#options' => drupal_map_assoc($YesNoOptions),
		'#empty_option' => t('- Select -'),
		'#required' => FALSE,
		 '#states' => array(
      		'visible' => array(
        		array('select[name="1"]' => array('value' => 'Sí')),
      			array('select[name="2"]' => array('value' => 'Sí')),
      			array('select[name="3"]' => array('value' => 'Sí')),
      		),
    	),
	);
	
	$form['laboral']['4_1'] = array(
			'#type' => 'textfield',
			'#title' => t('4.1 ¿Qué haces en ese trabajo?'),
			'#size' => 30,
			'#maxlength' => 30,
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
					),
			),
	);
	
	$_5Options = array(
			1 => t('Menos de una semana'),
			2 => t('1 a 3 semanas'),
			3 => t('1 a 3 meses'),
			4 => t('Más de 3 meses'),
	);
	
	$form['laboral']['5'] = array(
			'#type' => 'select',
			'#title' => t('5. ¿Cuánto tiempo tienes en este trabajo?'),
			'#options' => drupal_map_assoc($_5Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
				), 
					),
	);
	
	$_6Options = array(
			1 => t('Fijo'),
			2 => t('Temporal'),
			3 => t('Pasantía'),
			4 => t('Otro'),
	);
	
	$form['laboral']['6'] = array(
			'#type' => 'select',
			'#title' => t('6. ¿Este trabajo es...?'),
			'#options' => drupal_map_assoc($_6Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
					),
			),
	);

	$form['laboral']['6Otro'] = array(
		'#type' => 'textfield',
		'#title' => t('6.Otro (favor especificar):'),
		'#required' => FALSE,
		'#maxlength' => 50,
		'#states' => array(
				'visible' => array (
						array('select[name="1"]' => array('value' => 'Sí'), 'select[name="4"]' => array('value' => 'Sí'), 'select[name="6"]' => array('value' => 'Otro')),
						array('select[name="2"]' => array('value' => 'Sí'), 'select[name="4"]' => array('value' => 'Sí'), 'select[name="6"]' => array('value' => 'Otro')),
						array('select[name="3"]' => array('value' => 'Sí'), 'select[name="4"]' => array('value' => 'Sí'), 'select[name="6"]' => array('value' => 'Otro')),
				),
			),
	);
	
	$_6_1Options = array(
			1 => t('Con contrato'),
			2 => t('Sin contrato'),
			3 => t('Otro'),
	);
	
	$form['laboral']['6_1'] = array(
			'#type' => 'select',
			'#title' => t('6.1 ¿Bajo cuál condición?'),
			'#options' => drupal_map_assoc($_6_1Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
					),
			),
	);
	
	$form['laboral']['6_1Otro'] = array(
			'#type' => 'textfield',
			'#title' => t('6.1 Otro (favor especificar):'),
			'#required' => FALSE,
			'#maxlength' => 50,
			'#states' => array(
				'visible' => array (
						array('select[name="1"]' => array('value' => 'Sí'), 'select[name="4"]' => array('value' => 'Sí'), 'select[name="6_1"]' => array('value' => 'Otro')),
						array('select[name="2"]' => array('value' => 'Sí'), 'select[name="4"]' => array('value' => 'Sí'), 'select[name="6_1"]' => array('value' => 'Otro')),
						array('select[name="3"]' => array('value' => 'Sí'), 'select[name="4"]' => array('value' => 'Sí'), 'select[name="6_1"]' => array('value' => 'Otro')),
				),
			),
	);
	
	$_7Options = array(
			1 => t('Menos de 1,000'),
			2 => t('De 1,001 - 3,000'),
			3 => t('Más de 3,000'),
	);
	
	$form['laboral']['7'] = array(
			'#type' => 'select',
			'#title' => t('7. ¿Cuánto ganas en una semana?'),
			'#options' => drupal_map_assoc($_7Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
					),
					),
	);
	
	$form['laboral']['8'] = array(
			'#type' => 'select',
			'#title' => t('8. Cuando iniciaste el curso técnico ¿ya estabas en algún trabajo en el que te pagaban?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
					),
					),
	);
	
	$form['laboral']['8_1'] = array(
			'#type' => 'select',
			'#title' => t('8.1 ¿Consideras que tu trabajo actual es mejor que el anterior?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí')), 'select[name="8"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí')), 'select[name="8"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí')), 'select[name="8"]' => array('value' => 'Sí')),
					),
			),
	);
	
	$form['laboral']['9'] = array(
			'#type' => 'select',
			'#title' => t('9. ¿En los últimos 12 meses has hecho algún trabajo en el que te hayan pagado?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
					),
			),
	);
	
	$form['laboral']['9_1'] = array(
			'#type' => 'textfield',
			'#title' => t('9.1 ¿Qué hacías en ese trabajo?'),
			'#size' => 30,
			'#maxlength' => 30,
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
					),
			),
	);
	
	$form['laboral']['10'] = array(
			'#type' => 'select',
			'#title' => t('10. ¿Cuánto tiempo duraste en este trabajo?'),
			'#options' => drupal_map_assoc($_5Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
					),
			),
	);
	
	$form['laboral']['11'] = array(
			'#type' => 'select',
			'#title' => t('11. ¿Ese trabajo era...?'),
			'#options' => drupal_map_assoc($_6Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
					),
			),
	);
	
	$form['laboral']['11Otro'] = array(
			'#type' => 'textfield',
			'#title' => t('11.Otro (favor especificar):'),
			'#required' => FALSE,
			'#maxlength' => 50,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí')), 'select[name="11"]' => array('value' => 'Otro')),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí')), 'select[name="11"]' => array('value' => 'Otro')),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí')), 'select[name="11"]' => array('value' => 'Otro')),
					),
			),
	);
	
	$form['laboral']['11_1'] = array(
			'#type' => 'select',
			'#title' => t('11.1 ¿Bajo cuál condición?'),
			'#options' => drupal_map_assoc($_6_1Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
					),
			),
	);
	
	$form['laboral']['11_1Otro'] = array(
			'#type' => 'textfield',
			'#title' => t('11.1 Otro (favor especificar):'),
			'#required' => FALSE,
			'#maxlength' => 50,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí')), 'select[name="11_1"]' => array('value' => 'Otro')),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí')), 'select[name="11_1"]' => array('value' => 'Otro')),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí')), 'select[name="11_1"]' => array('value' => 'Otro')),
					),
			),
	);
	
	$form['laboral']['12'] = array(
			'#type' => 'select',
			'#title' => t('12. ¿Cuánto ganabas en una semana?'),
			'#options' => drupal_map_assoc($_7Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
							array('select[name="2"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
							array('select[name="3"]' => array('value' => 'Sí'), array('select[name="9"]' => array('value' => 'Sí'))),
					),
			),
	);
	
	$form['credits']['13'] = array(
			'#type' => 'select',
			'#title' => t('13. ¿Has recibido un préstamo a través del proyecto Alerta Joven para montar tu negocio?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
					),
			),
	);
	
	$form['credits']['14'] = array(
			'#type' => 'select',
			'#title' => t('14. ¿Tienes un negocio propio actualmente?'),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
							array('select[name="2"]' => array('value' => 'Sí')),
							array('select[name="3"]' => array('value' => 'Sí')),
					),
			),
	);
	
	$form['actions'] = array('#type' => 'actions');

	$form['actions']['cancel'] = array(
		'#type' => 'submit',
		'#prefix' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<div style="display: inline-block; width: 200px;" class = "remove"><br>',
		'#sufix' => '</div> <br>',
		'#value' => t('Cancelar'),
		'#limit_validation_errors' => array(),
		'#submit' => array('ajregistration_form_submit'),
		'#weight' => 100,
	);

	$form['actions']['submit'] = array(
		'#type' => 'submit',
		'#prefix' => '',
		'#sufix' => '',
		'#value' => t('Guardar'),
		'#weight' => 100,
	);

	return $form;
}

/**
 * This is the hook implementation for _form_submit
 * @param unknown $form
 * @param unknown $form_state
 */
function ajlabor_form_submit($form, &$form_state) {

	if ( $form_state['clicked_button']['#value'] === 'Cancelar' ) {
		drupal_set_message('Formulario descartado', 'warning');
		$form_state['redirect'] = 'mis-beneficiarios';
		return;
	}

	$urlParams = drupal_get_query_parameters();
	$uuid = $urlParams['uuid'];
	$provider_id = $urlParams['provider_id'];

	$beneficiary = _ajlabor_getBeneficiaryInfo($uuid);
	$beneficiaryDetails = $beneficiary['nombre'].' '.$beneficiary['apellido'].' ('.$uuid.')';

	_ajlabor_insert_data(
			$form_state['values']['1'],
			$form_state['values']['2'],
			$form_state['values']['3'],
			$form_state['values']['4'],
			$form_state['values']['4_1'],
			$form_state['values']['5'],
			$form_state['values']['6'],
			$form_state['values']['6Otro'],
			$form_state['values']['6_1'],
			$form_state['values']['6_1Otro'],
			$form_state['values']['7'],
			$form_state['values']['8'],
			$form_state['values']['8_1'],
			$form_state['values']['9'],
			$form_state['values']['9_1'],
			$form_state['values']['10'],
			$form_state['values']['11'],
			$form_state['values']['11Otro'],
			$form_state['values']['11_1'],
			$form_state['values']['11_1Otro'],
			$form_state['values']['12'],
			$form_state['values']['13'],
			$form_state['values']['14'],
			$uuid,
			$provider_id);

	drupal_set_message('La encuesta de Inserción Laboral ha sido guardado satisfactoriamente para <b>'.$beneficiaryDetails.'</b>!');

	$form_state['redirect'] = 'mis-beneficiarios';

}

/**
 *	Implements validation from the Form API.
 *
 * @param $form
 *   A structured array containing the elements and properties of the form.
 * @param $form_state
 *   An array that stores information about the form's current state
 *   during processing.
 */
 function ajlabor_form_validate($form, &$form_state) {

 	if (!isset($form['initial']['1'])) {
 		return;
 	}

 	$_1 = $form_state['values']['1'];
    $_2 = $form_state['values']['2'];
    $_3 = $form_state['values']['3'];
 	$_4 = $form_state['values']['4'];
    $_4_1 = $form_state['values']['4_1'];
    $_5 = $form_state['values']['5'];
 	$_6 = $form_state['values']['6'];
 	$_6Otro = $form_state['values']['6Otro'];
    $_6_1 = $form_state['values']['6_1'];
 	$_6_1Otro = $form_state['values']['6_1Otro'];
    $_7 = $form_state['values']['7'];
    $_8 = $form_state['values']['8'];
 	$_8_1 = $form_state['values']['8_1'];
 	$_9 = $form_state['values']['9'];
 	$_9_1 = $form_state['values']['9_1'];
 	$_10 = $form_state['values']['10'];
 	$_11 = $form_state['values']['11'];
 	$_11Otro = $form_state['values']['11Otro'];
 	$_11_1 = $form_state['values']['11_1'];
 	$_11_1Otro = $form_state['values']['11_1Otro'];
 	$_12 = $form_state['values']['12'];
 	$_13 = $form_state['values']['13'];
 	$_14 = $form_state['values']['14'];
 	

	// QUESTION 4 to 14 --------------------------------------------------------------
	if($_1 === 'Sí' || $_2 === 'Sí' || $_3 === 'Sí') {
	 	if (empty($_4)) {
			form_error($form['laboral']['4'], t('4. ¿Actualmente tienes un trabajo en el que te paguen?: Campo requerido'));
		} 
		if ($_4 === 'Sí') {
			if (empty($_5)) {
				form_error($form['laboral']['5'], t('5. ¿Cuánto tiempo tienes en este trabajo?: Campo requerido'));
			}
		}
		if ($_4 === 'Sí') {
		
		if (empty($_6)) {
			form_error($form['laboral']['6'], t('6. ¿Este trabajo es...?: Campo requerido'));
		}
		}
		if ($_4 === 'Sí') {
		
		if (empty($_6_1)) {
			form_error($form['laboral']['6_1'], t('6.1 ¿Bajo cuál condición?: Campo requerido'));
		}
		}
		if ($_4 === 'Sí') {
		
		if (empty($_7)) {
			form_error($form['laboral']['7'], t('7. ¿Cuánto ganas en una semana?: Campo requerido'));
		}
		}
		if ($_4 === 'Sí') {
		
		if (empty($_8)) {
			form_error($form['laboral']['8'], t('8. Cuando iniciaste el curso técnico ¿ya estabas en algún trabajo en el que te pagaban?: Campo requerido'));
		}}
		if (empty($_9)) {
			form_error($form['laboral']['9'], t('9. ¿En los últimos 12 meses has hecho algún trabajo en el que te hayan pagado?: Campo requerido'));
		}
		if ($_9 === 'Sí') {
		
		if (empty($_10)) {
			form_error($form['laboral']['10'], t('10. ¿Cuánto tiempo duraste en este trabajo?: Campo requerido'));
		}
		}
		if ($_9 === 'Sí') {
		
		if (empty($_11)) {
			form_error($form['laboral']['11'], t('11. ¿Ese trabajo era...?: Campo requerido'));
		}
		}
		if ($_9 === 'Sí') {
		
		if (empty($_11_1)) {
			form_error($form['laboral']['11_1'], t('11.1 ¿Bajo cuál condición?: Campo requerido'));
		}
		}
		if ($_9 === 'Sí') {
		
		if (empty($_12)) {
			form_error($form['laboral']['12'], t('12. ¿Cuánto ganabas en una semana?: Campo requerido'));
		}
		}
		if (empty($_13)) {
			form_error($form['credits']['13'], t('13. ¿Has recibido un préstamo a través del proyecto Alerta Joven para montar tu negocio?: Campo requerido'));
		}
		if (empty($_14)) {
			form_error($form['credits']['14'], t('14. ¿Tienes un negocio propio actualmente?: Campo requerido'));
		}
	}

	// QUESTION 4_1 --------------------------------------------------------------
	if ($_4 === 'Sí') {
		if (empty($_4_1)) {
			form_error($form['laboral']['4_1'], t('4.1 ¿Qué haces en ese trabajo?: Campo requerido'));
		}
	}

	// QUESTION 6Otro -------------------------------------------------------------------------------------
	if ($_6 === 'Otro') {
		if (empty($_6Otro)) {
			form_error($form['laboral']['6Otro'], t('6.Otro (favor especificar): Campo requerido'));
		}
	}
	
	// QUESTION 6.1 Otro -------------------------------------------------------------------------------------
	if ($_6_1 === 'Otro') {
		if (empty($_6_1Otro)) {
			form_error($form['laboral']['6_1Otro'], t('6.1 Otro (favor especificar): Campo requerido'));
		}
	}

	// QUESTION 8_1 --------------------------------------------------------------
	if ($_8 === 'Sí') {
		if (empty($_8_1)) {
				form_error($form['laboral']['8_1'], t('8.1 ¿Consideras que tu trabajo actual es mejor que el anterior?: Campo requerido'));
		}
	}
	
	// QUESTION 9_1 --------------------------------------------------------------
	if ($_9 === 'Sí') {
		if (empty($_9_1)) {
			form_error($form['laboral']['9_1'], t('9.1 ¿Qué hacías en ese trabajo?: Campo requerido'));
		}
	}
	
	// QUESTION 11Otro -------------------------------------------------------------------------------------
	if ($_11 === 'Otro') {
		if (empty($_11Otro)) {
			form_error($form['laboral']['11Otro'], t('11.Otro (favor especificar): Campo requerido'));
		}
	}
	
	// QUESTION 11.1 Otro -------------------------------------------------------------------------------------
	if ($_11_1 === 'Otro') {
		if (empty($_11_1Otro)) {
			form_error($form['laboral']['11_1Otro'], t('11.1 Otro (favor especificar): Campo requerido'));
		}
	}
 }

 /**
  * Implements the hook_permissions
  */
 function ajlabor_permission() {
	return array(
		'access ajlabor content' => array(
				'title' => t('Access content for ajlabor module'),
				'description' => t('Control the access for the Labor Survey form'),
		)
	);
 }


 /**
  *  Callback function that generates content
  */
function _ajlabor_page() {
	return drupal_get_form('ajlabor_form');
}

/**
 * Script to insert the new form data
 */
function _ajlabor_insert_data(
			$_1,
			$_2,
			$_3,
			$_4,
			$_4_1,
			$_5,
			$_6,
			$_6Otro,
			$_6_1,
			$_6_1Otro,
			$_7,
			$_8,
			$_8_1,
			$_9,
			$_9_1,
			$_10,
			$_11,
			$_11Otro,
			$_11_1,
			$_11_1Otro,
			$_12,
			$_13,
			$_14,
			$uuid,
			$provider_id) {
	global $user;
	$currentDate = format_date(time(), 'custom', 'Y-m-d H:i:s');

	$tableFields =  array(
		'created' => $currentDate,
		'uuid' => $uuid,
		'provider_id' => $provider_id,
		'user_name' => $user->name,
		'1_HasparticipadoenalguncursodelproyectoAlerta' => $_1,
		'2_Hasparticipadoenalguntallerocursodelproyecto' => $_2,
		'3_Hasparticipadoenalguntallerocursodelproyecto' => $_3,
		'4_Actualmentetienesuntrabajoenel' => $_4,
		'4_1Quehacesenesetrabajo' => $_4_1,
		'5_Cuantotiempotienesenestetrabajo' => $_5,
		'6_Estetrabajoes' => $_6,
		'6_Otrofavorespecificar' => $_6Otro,
		'6_1Bajocualcondicion' => $_6_1,
		'6_1Otrofavorespecificar' => $_6_1Otro,
		'7_Cuantoganasenunasemana' => $_7,
		'8_Cuandoiniciasteelcursotecnicoyaestabas' => $_8,
		'8_1Considerasquetutrabajoactual' => $_8_1,
		'9_Enlosultimos12meseshashecho' => $_9,
		'9_1Quehaciasenesetrabajo' => $_9_1,
		'10_Cuantotiempodurasteenestetrabajo' => $_10,
		'11_Esetrabajoera' => $_11,
		'11_Otrofavorespecificar' => $_11Otro,
		'11_1Bajocualcondicion' => $_11,
		'11_1Otrofavorespecificar' => $_11_1Otro,
		'12_Cuantoganabasenunasemana' => $_12,
		'13_Hasrecibidounprestamoatravesdelproyecto' => $_13,
		'14_Tienesunnegociopropio' => $_14,
	);

	$labor_entry = db_insert('aj_labor')
	->fields($tableFields);
	$labor_entry->execute();

// 	$tableFieldsPrograms = array(
// 		'created' => $currentDate,
// 		'uuid' => $uuid,
// 		'provider_id' => $provider_id,
// 		'answer' => 'Participado',
// 	);

// 	foreach ($_14A as $programParticipation) {
// 		if ($programParticipation !== 0) {
// 			$tableFieldsPrograms['program_id'] = $programParticipation;
// 			$exit_programs_entry = db_insert('aj_exit_programs')
// 			->fields($tableFieldsPrograms);
// 			$exit_programs_entry->execute();
// 		}
// 	}

// 	$tableFieldsPrograms['answer'] = 'Completado';
// 	foreach ($_14B as $programCompleted) {
// 		if ($programCompleted !== 0) {
// 			$tableFieldsPrograms['program_id'] = $programCompleted;
// 			$exit_programs_entry = db_insert('aj_exit_programs')
// 			->fields($tableFieldsPrograms);
// 			$exit_programs_entry->execute();
// 		}
// 	}
}


/**
 * Get the beneficiary info
 */
function _ajlabor_getBeneficiaryInfo($uuid) {

	$query = db_select('aj_registration', 'reg');
	$query->fields('reg', array('nombre', 'apellido', 'uuid'));
	$query->condition('uuid', $uuid);
	$query->orderBy('nombre', 'ASC');
	$query->addExpression("DATE_FORMAT(FROM_DAYS(DATEDIFF(DATE_FORMAT(NOW(), '%Y-%m-%d'), dob)), '%Y')+0", 'edad');
	$query->range(0,1);

	$result = $query->execute();
	return $result->fetchAssoc();
}

/**
 * Checks if a given uuid already has a labor entry in the database
 */
function _ajlabor_alreadyExist($uuid) {

	$query = db_select('aj_labor', 'ajlabor');
	$query->fields('ajlabor', array('uuid'));
	$query->condition('uuid', $uuid);
	$query->range(0,1);

	$result = $query->execute();
	$entry =  $result->fetchAssoc();

	return !empty($entry);
}
