<?php

/**
 * @filesource
 * This is the hook_help implementation
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function ajlabor_help($path, $arg) {
	switch ($path) {
		case "admin/help#ajlabor":
			return '<p>' . t("Implementation of the Labor Survey Form") . '</p>';
			break;
	}
}

/**
 *Implements the hook_menu
 */
 function ajlabor_menu() {
	$items = array();

	$items['ajlabor'] = array(
		'title' => 'Labor Survey form',
		'description' => 'Form to collect data of a Labor Insertion participant',
		'page callback' => '_ajlabor_page',
    	'page arguments' => array('ajlabor_form'),
		'access arguments' => array('access ajlabor content'),
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
 }

 /**
  *  Page callback: Current users settings
  *  @see current_users_menu()
  */
function ajlabor_form($form, &$form_state) {

	$urlParams = drupal_get_query_parameters();
	$uuid = $urlParams['uuid'];
	$editing = false;

	$beneficiary = _ajlabor_getBeneficiaryInfo($uuid);
	$beneficiaryDetails = $beneficiary['nombre'].' '.$beneficiary['apellido'].' ('.$uuid.'). Su edad actual es '. $beneficiary['edad']. ' años';

	if (!_ajbeneficiaryEligible($uuid)) {
		drupal_set_message(t('Este beneficiario no ha participado en los programas Capacitación Técnico vocacional,
				Microcréditos, Auto empleo/Empredurismo o La Compañía: <b>'.$beneficiaryDetails.'</b>'), 'error');
		$form['actions']['cancel'] = array(
				'#markup' => l(t('Volver a Lista de Beneficiarios'), 'mis-beneficiarios'),
		);
		return $form;
	}
	if (_aj_exit_($uuid)) {
	
		drupal_set_message(t('Ya existe un Formulario de Salida disponible para <b>'.$beneficiaryDetails.'</b>. No se puede editar este contacto'), 'warning');
		$form['actions']['cancel'] = array(
				'#markup' => l(t('Volver a Lista de Beneficiarios'), 'mis-beneficiarios'),
		);
		return $form;
	}
	
	if (_ajlabor_alreadyExist($uuid)) {
// 		if (!_ajlabor_isEditable($uuid)) {
// 			drupal_set_message(t('La Encuesta Laboral existente no cumple las condiciones para ser editada: el beneficiario ya tiene trabajo
// 			    o ha trabajado en los últimos 12 meses. Beneficiario: <b>'.$beneficiaryDetails.'</b>'), 'error');
// 			$form['actions']['cancel'] = array(
// 					'#markup' => l(t('Volver a Lista de Beneficiarios'), 'mis-beneficiarios'),
// 			);
// 			return $form;
// 		} else {
			$editing = true;
			$label = '<p>Estás <b>****EDITANDO****</b> una Encuesta de Inserción Laboral para <b>'.$beneficiaryDetails.'</b></p>';
			$existingLaborForm = _ajlabor_getExistingLaborForm($uuid);
// 		}
	} else {
		$label = '<p>Estás creando una <b>NUEVA</b> Encuesta de Inserción Laboral para <b>'.$beneficiaryDetails.'</b></p>';
	}
	
	$form['welcome'] = array(
	  '#markup' => $label,
	);
	
	//  Tab 1
	$form['initial'] = array(
			'#type'  => 'fieldset',
			'#title' => t('Participación en el programa'),
			'#collapsible' => true,
			'#collapsed' => $editing,
	);
	
	// Tab 2
	$form['laboral'] = array(
    	'#type'  => 'fieldset',
    	'#title' => t('Condición Laboral'),
    	'#collapsible' => true,
    	'#collapsed' => FALSE,
		'#states' => array(
				'visible' => array(
						array('select[name="1"]' => array('value' => 'Sí')),
				),
		),
	);

	// Tab 3
	$form['credits'] = array(
    	'#type'  => 'fieldset',
    	'#title' => t('Obtención de Microcréditos'),
    	'#collapsible' => true,
    	'#collapsed' => FALSE,
    	'#group' => 'group_tabs',
			'#states' => array('visible' => array(array('select[name="1"]' => array('value' => 'Sí')))),
	);
	
	//  Tab 4
	$form['end'] = array(
	    '#type'  => 'fieldset',
	    '#title' => t('Contacto con el participante'),
	    '#collapsible' => true,
	    '#collapsed' => $editing,
	);

	$YesNoOptions = array(
		1 => t('Sí'),
		2 => t('No'),
	);
	
	$form['initial']['0'] = array(
	    '#type' => 'date',
	    '#title' => t('1. Fecha de llenado:'),
	    '#default_value' => (isset($existingLaborForm)? array(
	        'year' => date("Y", strtotime($existingLaborForm['0_fechadellenado'])),
	        'month' => date("m", strtotime($existingLaborForm['0_fechadellenado'])),
	        'day' => date("d", strtotime($existingLaborForm['0_fechadellenado']))
	    ):null),
	    '#required' => TRUE,
	    '#disabled' => $editing,
	);

	$form['initial']['1'] = array(
		'#type' => 'select',
		'#title' => t('2. ¿Has participado en algún curso del proyecto Alerta Joven en el que te enseñaron algo que te puede servir para trabajar?'),
		'#default_value' => (isset($existingLaborForm)? $existingLaborForm['1_HasparticipadoenalguncursodelproyectoAlerta']:null),
		'#options' => drupal_map_assoc($YesNoOptions),
		'#required' => TRUE,
		'#disabled' => $editing,
	);
	
	$_cursos = array(
	    1 => t('Programación Básica (Codificación)'),
	    2 => t('Redes de información'),
	    3 => t('Desarrollo de Software'),
	    4 => t('Receción de Hoteles'),
	    5 => t('Emprendimiento/Autoempleo'),
	    6 => t('Auxiliar de Farmacia'),
	    7 => t('Panes Domésticos y Europeos'),
	    8 => t('Pulidor de joyas'),
	    9 => t('Moldeo por inyección'),
	    10 => t('Capacitación propia de la industria'),
	    11 => t('Camarero'),
	    12 => t('Industrialización del cacao'),
	    13 => t('Bartender'),
	    14 => t('Pantrista (Cocina doméstica)'),
	    15 => t('Call center'),
	    16 => t('Guía turístico'),
	    17 => t('Auxiliar de calidad'),
	    18 => t('Ensamblador de equipos'),
	    19 => t('Secretariado ejecutivo'),
	    20 => t('Operador por teléfono'),
	    21 => t('Paguete de oficina'),
	    22 => t('Otro'),
	);
	
	$form['laboral']['4_3'] = array(
	    '#type' => 'select',
	    '#title' => t('2.1 ¿Cuál curso realizaste?'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['4_3Cualcursorealizaste']:null),
	    '#options' => drupal_map_assoc($_cursos),
	    '#empty_option' => t('- Select -'),
	    '#required' => FALSE,
	    '#states' => array(
	      		'visible' => array(array('select[name="1"]' => array('value' => 'Sí'))),
	    ),
	);
	
	$form['laboral']['4_3Otro'] = array(
	    '#type' => 'textfield',
	    '#title' => t('2.1.Otro (favor especificar):'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['4_3Otrofavorespecificar']:null),
	    '#required' => FALSE,
	    '#maxlength' => 50,
	    '#states' => array(
	        'visible' => array (
						array('select[name="1"]' => array('value' => 'Sí'), 'select[name="4_3"]' => array('value' => 'Otro')),
	            ),
	    ),
	);

	$form['laboral']['4'] = array(
		'#type' => 'select',
		'#title' => t('3. ¿Después de haber terminado tu capacitación técnica con Alerta Joven, conseguiste un trabajo o pasantía en el que te paguen?'),
		'#default_value' => (isset($existingLaborForm)? $existingLaborForm['4_Actualmentetienesuntrabajoenel']:null),
		'#options' => drupal_map_assoc($YesNoOptions),
		'#empty_option' => t('- Select -'),
		'#required' => FALSE,
		 '#states' => array(
      		'visible' => array(
        		array('select[name="1"]' => array('value' => 'Sí')),
      		),
    	),
	);
	
	$form['laboral']['4_4'] = array(
	    '#type' => 'textfield',
	    '#title' => t('4.  ¿Dónde? <br> Nombre de la empresa:'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['4_4Nombredelaempresa']:null),
	    '#required' => FALSE,
	    '#maxlength' => 50,
	    '#states' => array(
	        'visible' => array (
					array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
	            ),
	    ),
	);
	
	$form['laboral']['4_5'] = array(
	    '#type' => 'textfield',
	    '#title' => t('4.1 Teléfono de la empresa:'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['4_5Telefonodelaempresa']:null),
	    '#required' => FALSE,
	    '#maxlength' => 16,
	    '#states' => array(
	        'visible' => array (
	            array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
	        ),
	    ),
	);
	
	$form['laboral']['4_2'] = array(
	    '#type' => 'select',
	    '#title' => t('5. ¿Es éste tu primer empleo?'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['4_2Esestetuprimerempleo']:null),
	    '#options' => drupal_map_assoc($YesNoOptions),
	    '#empty_option' => t('- Select -'),
	    '#required' => FALSE,
	    '#states' => array(
	      		'visible' => array(
					array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
	      		),
	    ),
	);
	
	$_empleo = array(
	    1 => t('Programador básico'),
	    2 => t('Soporte en redes de información'),
	    3 => t('Desarrollo de Software'),
	    4 => t('Pulidor de joyas'),
	    5 => t('Operario'),
	    6 => t('Vendedor'),
	    7 => t('Brindo servicio al cliente'),
	    8 => t('Guía turístico'),
	    9 => t('Camarero/a'),
	    10 => t('Supervisor'),
	    11 => t('Seguridad'),
	    12 => t('Otro'), 
	);
	
	$form['laboral']['4_1'] = array(
			'#type' => 'select',
			'#title' => t('6. ¿Qué haces en ese trabajo?'),
			'#default_value' => (isset($existingLaborForm)? $existingLaborForm['4_1Quehacesenesetrabajo']:null),
			'#options' => drupal_map_assoc($_empleo),
			'#empty_option' => t('- Select -'),
	        '#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
					),
			),
	);
	
	$form['laboral']['4_1Otro'] = array(
		'#type' => 'textfield',
		'#title' => t('6.1.Otro (favor especificar):'),
		'#default_value' => (isset($existingLaborForm)? $existingLaborForm['4_1Otrofavorespecificar']:null),
		'#required' => FALSE,
		'#maxlength' => 50,
		'#states' => array(
				'visible' => array (
						array('select[name="1"]' => array('value' => 'Sí'), 'select[name="4"]' => array('value' => 'Sí'), 'select[name="4_1"]' => array('value' => 'Otro')),
				),
			),
	);
	
	$_5Options = array(
			1 => t('Menos de una semana'),
			2 => t('1 a 4 semanas'),
			3 => t('1 a 3 meses'),
			4 => t('Más de 3 meses'),
	);
	
	$form['laboral']['5'] = array(
			'#type' => 'select',
			'#title' => t('7. ¿Cuánto tiempo tienes en este trabajo?'),
			'#default_value' => (isset($existingLaborForm)? $existingLaborForm['5_Cuantotiempotienesenestetrabajo']:null),
			'#options' => drupal_map_assoc($_5Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
				), 
					),
	);
	
	$_6Options = array(
			1 => t('Fijo'),
			2 => t('Temporal'),
			3 => t('Pasantía'),
	        4 => t('Ocasional'),
	);
	
	$form['laboral']['6'] = array(
			'#type' => 'select',
			'#title' => t('8. ¿Este trabajo es...?'),
			'#default_value' => (isset($existingLaborForm)? $existingLaborForm['6_Estetrabajoes']:null),
			'#options' => drupal_map_assoc($_6Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
					),
			),
	);

	$form['laboral']['6Otro'] = array(
		'#type' => 'textfield',
		'#title' => t('8.Otro (favor especificar):'),
		'#default_value' => (isset($existingLaborForm)? $existingLaborForm['6_Otrofavorespecificar']:null),
		'#required' => FALSE,
		'#maxlength' => 50,
		'#states' => array(
				'visible' => array (
						array('select[name="1"]' => array('value' => 'Sí'), 'select[name="4"]' => array('value' => 'Sí'), 'select[name="6"]' => array('value' => 'Otro')),
				),
			),
	);
	
	$_7Options = array(
			1 => t('Menos de 4,000'),
			2 => t('De 4,001 - 8,000'),
			3 => t('De 8,001 - 12,000'),
	        4 => t('De 12,001 - 15,000'),
	        5 => t('Más de 15,000'),   
	);
	
	$form['laboral']['7'] = array(
			'#type' => 'select',
			'#title' => t('9. ¿Cuánto ganas en un mes?'),
			'#default_value' => (isset($existingLaborForm)? $existingLaborForm['7_Cuantoganasenunasemana']:null),
			'#options' => drupal_map_assoc($_7Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
							array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
					),
					),
	);
	
	$form['laboral']['8'] = array(
			'#type' => 'select',
			'#title' => t('10. ¿Ya estabas trabajando antes de la capacitación de Alerta Joven?'),
			'#default_value' => (isset($existingLaborForm)? $existingLaborForm['8_Cuandoiniciasteelcursotecnicoyaestabas']:null),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
					    array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
					    array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'No'))),
					),
					),
	);
	
	$form['laboral']['8_0'] = array(
	    '#type' => 'select',
	    '#title' => t('11. ¿Cambiaste de lugar de trabajo después de la capacitación de Alerta Joven?'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['8_3Cambiastedelugardetrabajodespues']:null),
	    '#options' => drupal_map_assoc($YesNoOptions),
	    '#empty_option' => t('- Select -'),
	    '#required' => FALSE,
	    '#states' => array(
	        'visible' => array (
	            array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
	            array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'No'))),
	        ),
	    ),
	);
	
	$_8_1Options = array(
	    1 => t('Sí'),
	    2 => t('No'),
	);
	
	$form['laboral']['8_1'] = array(
			'#type' => 'select',
			'#title' => t('12. ¿Consideras que tu trabajo actual es mejor que el anterior?'),
			'#default_value' => (isset($existingLaborForm)? $existingLaborForm['8_1Considerasquetutrabajoactual']:null),
			'#options' => drupal_map_assoc($_8_1Options),
			'#empty_option' => t('- Select -'),
			'#required' => FALSE,
			'#states' => array(
					'visible' => array (
					    array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
					    array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'No'))),
					),
			),
	);
	
	$whyBetterJobOptions = array(
	    1 => t('Mejor salario'),
	    2 => t('Ambiente laboral'),
	    3 => t('Seguro médico'),
	    4 => t('Seguridad laboral'),
	    5 => t('Mejor horario laboral'),
	    6 => t('Crecimiento profesional'),
	    7 => t('Estabilidad en el puesto'),
	    8 => t('Otro'),
	);
	
	$form['laboral']['8_2'] = array(
	    '#type' => 'select',
	    '#title' => t('13. ¿Por qué considera que es un mejor empleo?'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['8_2Porqueconsideraqueesunmejorempleo']:null),
	    '#options' => drupal_map_assoc($whyBetterJobOptions),
	    '#empty_option' => t('- Select -'),
	    '#required' => FALSE,
	    '#states' => array(
	        'visible' => array (
	            array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'Sí'))),
	            array('select[name="1"]' => array('value' => 'Sí'), array('select[name="4"]' => array('value' => 'No'))),
	        ),
	    ),
	);
	
	$form['laboral']['8_2Otro'] = array(
	    '#type' => 'textfield',
	    '#title' => t('13.Otro (favor especificar):'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['8_2Otrofavorespecificar']:null),
	    '#required' => FALSE,
	    '#maxlength' => 30,
	    '#states' => array(
	        'visible' => array (
	            array('select[name="1"]' => array('value' => 'Sí'), 'select[name="4"]' => array('value' => 'Sí'), 'select[name="8_2"]' => array('value' => 'Otro')),
	            array('select[name="1"]' => array('value' => 'Sí'), 'select[name="4"]' => array('value' => 'No'), 'select[name="8_2"]' => array('value' => 'Otro')),
	        ),
	    ),
	);
		
	$form['credits']['13'] = array(
			'#type' => 'select',
			'#title' => t('14. ¿Has recibido algún apoyo del proyecto Alerta Joven para montar un negocio/emprender?'),
			'#default_value' => (isset($existingLaborForm)? $existingLaborForm['13_Hasrecibidounprestamoatravesdelproyecto']:null),
			'#options' => drupal_map_assoc($YesNoOptions),
			'#empty_option' => t('- Select -'),
			'#disabled' => $editing,
			'#required' => FALSE,
			'#states' => array(
					'visible' => array(
							array('select[name="1"]' => array('value' => 'Sí')),
					),
			),
	);
	
	$typeOfSupport = array(
	    1 => t('Capacitación emprendimiento'),
	    2 => t('Coaching'),
	    3 => t('Monetario'),
	);
	
	$form['credits']['15'] = array(
	    '#type' => 'select',
	    '#title' => t('15. ¿Qué tipo de apoyo?'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['15_Quetipodeapoyo']:null),
	    '#options' => drupal_map_assoc($typeOfSupport),
	    '#empty_option' => t('- Select -'),
	    '#required' => FALSE,
	    '#states' => array(
	        'visible' => array(
	            array('select[name="1"]' => array('value' => 'Sí'), array('select[name="13"]' => array('value' => 'Sí'))),
	        ),
	    ),
	);
	
	$form['credits']['13_1'] = array(
	    '#type' => 'textfield',
	    '#title' => t('15.1 ¿Cuánto recibiste?'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['13_1Quemontorecibiste']:null),
		'#required' => FALSE,
		'#maxlength' => 15,
	    '#states' => array(
	        'visible' => array (
	            array('select[name="1"]' => array('value' => 'Sí'), array('select[name="13"]' => array('value' => 'Sí'), 'select[name="15"]' => array('value' => 'Monetario'))),
	        ),
	    ),
	);
	
	$StablishNewBusiness = array(
	    1 => t('Sí'),
	    2 => t('No'),
	    3 => t('Ya tenía un negocio'),
	);
	
	$form['credits']['14'] = array(
	    '#type' => 'select',
	    '#title' => t('16. ¿Pudiste montar tu negocio después del apoyo recibido de Alerta Joven?'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['14_Tienesunnegociopropio']:null),
	    '#options' => drupal_map_assoc($StablishNewBusiness),
	    '#empty_option' => t('- Select -'),
	    '#required' => FALSE,
	    '#states' => array(
	        'visible' => array(
	            array('select[name="1"]' => array('value' => 'Sí'), 'select[name="13"]' => array('value' => 'Sí')),
	        ),
	    ),
	);
	
	$gainsOptions = array(
	    1 => t('Menos de 3,000 pesos'),
	    2 => t('De 4,001 - 8,000 pesos'),
	    3 => t('De 8,001 - 12,000 pesos'),
	    4 => t('Más de 12,000 pesos'),
	);
	
	$form['credits']['16'] = array(
	    '#type' => 'select',
	    '#title' => t('17. ¿Si ya tenías un negocio, consideras que después del soporte de Alerta Joven ha mejorado?'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['16_Siyateniasunnegocioconsiderasquedespuesdel']:null),
	    '#options' => drupal_map_assoc($YesNoOptions),
	    '#empty_option' => t('- Select -'),
	    '#required' => FALSE,
	    '#states' => array(
	        'visible' => array(
	            array('select[name="1"]' => array('value' => 'Sí'), array('select[name="13"]' => array('value' => 'Sí')), 'select[name="14"]' => array('value' => 'Sí')),
	        ),
	    ),
	);
	
	$howTheBusinessHasImproved = array(
	    1 => t('Mejores ingresos'),
	    2 => t('Mejor planificación'),
	    3 => t('Mejor atención al cliente'),
	    4 => t('Más productos o servicios ofrecidos'),
	    5 => t('Mejor ubicación'),
	    6 => t('Mayor conocimiento de tu negocio'),
	);
	
	$form['credits']['17'] = array(
	    '#type' => 'select',
	    '#title' => t('18. ¿Cómo ha mejorado?'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['17_Comohamejorado']:null),
	    '#options' => drupal_map_assoc($howTheBusinessHasImproved),
	    '#empty_option' => t('- Select -'),
	    '#required' => FALSE,
	    '#states' => array(
	        'visible' => array(
	            array('select[name="1"]' => array('value' => 'Sí'), array('select[name="13"]' => array('value' => 'Sí')), 'select[name="14"]' => array('value' => 'Sí'), 'select[name="16"]' => array('value' => 'Sí')),
	        ),
	    ),
	);
	
	$form['credits']['13_2'] = array(
	    '#type' => 'select',
	    '#title' => t('19. ¿Qué monto genera tu negocio mensualmente?'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['13_2Quemontogeneratunegociomensualmente']:null),
	    '#options' => drupal_map_assoc($gainsOptions),
	    '#empty_option' => t('- Select -'),
	    '#required' => FALSE,
	    '#states' => array(
	        'visible' => array(
	            array('select[name="1"]' => array('value' => 'Sí'), array('select[name="13"]' => array('value' => 'Sí')), 'select[name="14"]' => array('value' => 'Sí'), 'select[name="16"]' => array('value' => 'Sí')),
	        ),
	    ),
	);
	
	$businessTiersOptions = array(
	    1 => t('Comercio'),
	    2 => t('Servicio'),
	    3 => t('Industrial'),
	    4 => t('Tecnología'),
	);
	
	$form['credits']['14_1'] = array(
	    '#type' => 'select',
	    '#title' => t('20. ¿A qué se dedica tu negocio?'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['14_1Aquesededicatunegocio']:null),
	    '#options' => drupal_map_assoc($businessTiersOptions),
	    '#empty_option' => t('- Select -'),
	    '#required' => FALSE,
	    '#states' => array(
	        'visible' => array(
	            array('select[name="1"]' => array('value' => 'Sí'), array('select[name="13"]' => array('value' => 'Sí')), 'select[name="14"]' => array('value' => 'Sí'), 'select[name="16"]' => array('value' => 'Sí')),
	            ),
	    ),
	);
	
	$form['end']['18'] = array(
	    '#type' => 'textfield',
	    '#title' => t('21. ¿Quién contactó al participante?'),
	    '#default_value' => (isset($existingLaborForm)? $existingLaborForm['18_Quiencontactoalparticipante']:null),
	    '#required' => TRUE,
	    '#maxlength' => 15
	);
	
	$form['actions'] = array('#type' => 'actions');

	$form['actions']['cancel'] = array(
		'#type' => 'submit',
		'#prefix' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<div style="display: inline-block; width: 200px;" class = "remove"><br>',
		'#sufix' => '</div> <br>',
		'#value' => t('Cancelar'),
		'#limit_validation_errors' => array(),
		'#submit' => array('ajregistration_form_submit'),
		'#weight' => 100,
	);

	$form['actions']['submit'] = array(
		'#type' => 'submit',
		'#prefix' => '',
		'#sufix' => '',
		'#value' => t('Guardar'),
		'#weight' => 100,
	);

	return $form;
}

/**
 * This is the hook implementation for _form_submit
 * @param unknown $form
 * @param unknown $form_state
 */
function ajlabor_form_submit($form, &$form_state) {

	if ( $form_state['clicked_button']['#value'] === 'Cancelar' ) {
		drupal_set_message('Formulario descartado', 'warning');
		$form_state['redirect'] = 'mis-beneficiarios';
		return;
	}

	$urlParams = drupal_get_query_parameters();
	$uuid = $urlParams['uuid'];
	$provider_id = $urlParams['provider_id'];

	$beneficiary = _ajlabor_getBeneficiaryInfo($uuid);
	$beneficiaryDetails = $beneficiary['nombre'].' '.$beneficiary['apellido'].' ('.$uuid.')';
	
	_ajlabor_insert_data(
	        $form_state['values']['0'],	   
			$form_state['values']['1'],
	        $form_state['values']['4_3'],
	        $form_state['values']['4_3Otro'],
			$form_state['values']['4'],
	        $form_state['values']['4_4'],
	        $form_state['values']['4_5'],
	        $form_state['values']['4_2'],
			$form_state['values']['4_1'],
	        $form_state['values']['4_1Otro'],
			$form_state['values']['5'],
			$form_state['values']['6'],
			$form_state['values']['6Otro'],
			$form_state['values']['7'],
			$form_state['values']['8'],
			$form_state['values']['8_1'],
	        $form_state['values']['8_2'],
	        $form_state['values']['8_2Otro'],
	        $form_state['values']['8_0'],
			$form_state['values']['13'],
	        $form_state['values']['13_1'],
	        $form_state['values']['13_2'],
			$form_state['values']['14'],
	        $form_state['values']['14_1'],
	        $form_state['values']['15'],
  	        $form_state['values']['16'],
  	        $form_state['values']['17'],
	        $form_state['values']['18'],
			$uuid,
			$provider_id);

	drupal_set_message('La encuesta de Inserción Laboral ha sido guardada satisfactoriamente para <b>'.$beneficiaryDetails.'</b>!');

	$form_state['redirect'] = 'mis-beneficiarios';

}

/**
 *	Implements validation from the Form API.
 *
 * @param $form
 *   A structured array containing the elements and properties of the form.
 * @param $form_state
 *   An array that stores information about the form's current state
 *   during processing.
 */
 function ajlabor_form_validate($form, &$form_state) {   
   
 	if (!isset($form['initial']['1'])) {
 		return;
 	}

 	$_1 = $form_state['values']['1'];
    $_4_3 = $form_state['values']['4_3'];
    $_4_3Otro = $form_state['values']['4_3Otro'];
 	$_4 = $form_state['values']['4'];
 	$_4_4 = $form_state['values']['4_4'];
 	$_4_5 = $form_state['values']['4_5'];
 	$_4_2 = $form_state['values']['4_2'];
    $_4_1 = $form_state['values']['4_1'];
    $_4_1Otro = $form_state['values']['4_1Otro'];
    $_5 = $form_state['values']['5'];
 	$_6 = $form_state['values']['6'];
 	$_6Otro = $form_state['values']['6Otro'];
    $_7 = $form_state['values']['7'];
    $_8 = $form_state['values']['8'];
 	$_8_1 = $form_state['values']['8_1'];
 	$_8_2 = $form_state['values']['8_2'];
 	$_8_2Otro = $form_state['values']['8_2Otro'];
 	$_8_0 = $form_state['values']['8_0'];
 	$_13 = $form_state['values']['13'];
 	$_13_1 = $form_state['values']['13_1'];
 	$_13_2 = $form_state['values']['13_2'];
 	$_14 = $form_state['values']['14'];
 	$_14_1 = $form_state['values']['14_1'];
 	$_15 = $form_state['values']['15'];
 	$_16 = $form_state['values']['16'];
 	$_17 = $form_state['values']['17'];
 	 	
	if($_1 === 'Sí') {
	  if (empty($_4_3)) {
	    form_error($form['laboral']['4_3'], t('2.1. ¿Cuál curso realizaste?: Campo requerido'));
	  }
	  
	 	if (empty($_4)) {
			form_error($form['laboral']['4'], t('3. ¿Después de haber terminado tu capacitación técnica con Alerta Joven, conseguiste un trabajo o pasantía en el que te paguen?: Campo requerido'));
		} 
		
		if ($_4 === 'Sí') {
		  if (empty($_4_4)) {
		    form_error($form['laboral']['4_4'], t('4. Nombre de la empresa: Campo requerido'));
		  }
		} else {
		  $form_state['values']['4_4'] = '';
		}
		
		if ($_4 === 'Sí') {
		  if (empty($_4_5)) {
		    form_error($form['laboral']['4_5'], t('4.1 Teléfono de la empresa: Campo requerido'));
		  }
		} else {
		  $form_state['values']['4_5'] = '';
		}
		
		if ($_4 === 'Sí') {
		  if (empty($_4_2)) {
		    form_error($form['laboral']['4_2'], t('5. ¿Es éste tu primer empleo?: Campo requerido'));
		  }
		} else {
		  $form_state['values']['4_2'] = '';
		}
		
		if ($_4 === 'Sí') {
		  if (empty($_4_1)) {
		    form_error($form['laboral']['4_1'], t('6. ¿Qué haces en ese trabajo?: Campo requerido'));
		  }
		} else {
		  $form_state['values']['4_1'] = '';
		  $form_state['values']['4_1Otro'] = '';
		}
		
		if ($_4 === 'Sí') {
			if (empty($_5)) {
				form_error($form['laboral']['5'], t('7. ¿Cuánto tiempo tienes en este trabajo?: Campo requerido'));
			}
		} else {
			$form_state['values']['5'] = '';
		}
		
		if ($_4 === 'Sí') {
			if (empty($_6)) {
				form_error($form['laboral']['6'], t('8. ¿Este trabajo es...?: Campo requerido'));
			}
		} else {
			$form_state['values']['6'] = '';
			$form_state['values']['6Otro'] = '';
		}
		
		if ($_4 === 'Sí') {
			if (empty($_7)) {
				form_error($form['laboral']['7'], t('9. ¿Cuánto ganas en un mes?: Campo requerido'));
			}
		} else {
			$form_state['values']['7'] = '';
		}
		
		if($_4 === 'Sí'|| $_4 === 'No') {
		  if (empty($_8)) {
		    form_error($form['laboral']['8'], t('10. ¿Ya estabas trabajando antes de la capacitación de Alerta Joven?: Campo requerido'));
		  }
		} else {
		  $form_state['values']['8'] = '';
		}
		
		
		if($_4 === 'Sí'|| $_4 === 'No') {
		  if (empty($_8_0)) {
		    form_error($form['laboral']['8_0'], t('11. ¿Cambiaste de lugar de trabajo después de la capacitación de Alerta Joven?: Campo requerido'));
		  }
		} else {
		  $form_state['values']['8_0'] = '';
		}
		
		if($_4 === 'Sí'|| $_4 === 'No') {
		  if (empty($_8_1)) {
		    form_error($form['laboral']['8_1'], t('12. ¿Consideras que tu trabajo actual es mejor que el anterior?: Campo requerido'));
		  }
		} else {
		  $form_state['values']['8_1'] = '';
		}
		
// 		if($_4 === 'Sí'|| $_4 === 'No') {
// 		  if (empty($_8_2)) {
// 		    form_error($form['laboral']['8_2'], t('13. ¿Por qué considera que es un mejor empleo?: Campo requerido'));
// 		  }
// 		} else {
// 		  $form_state['values']['8_2'] = '';
// 		}
		
		if (empty($_13)) {
			form_error($form['credits']['13'], t('14. ¿Has recibido algún apoyo del proyecto Alerta Joven para montar un negocio/emprender?: Campo requerido'));
		}
		
		if ($_13 === 'Sí') {
		  if (empty($_15)) {
		    form_error($form['credits']['15'], t('15. ¿Qué tipo de apoyo?: Campo requerido'));
		  }
		} else {
		  $form_state['values']['15'] = '';
		}
				
		if ($_13 === 'Sí') {
		  if ($_15 === 'Monetario') {
		    if (empty($_13_1)) {
		      form_error($form['credits']['13_1'], t('15.1 ¿Cuánto recibiste?: Campo requerido'));
		    } 
		  } else {
		    $form_state['values']['13_1'] = '';
		  }
		}
				
		if ($_13 === 'Sí') {
		  if (empty($_14)) {
		    form_error($form['credits']['14'], t('16. ¿Pudiste montar tu negocio después del apoyo recibido de Alerta Joven?: Campo requerido'));
		  }
		} else {
		  $form_state['values']['14'] = '';
		  $form_state['values']['16'] = '';
		  $form_state['values']['17'] = '';
		  $form_state['values']['13_2'] = '';
		  $form_state['values']['14_1'] = '';
		}
		print($form_state['values']['16']);
		
		if (empty($_14) || $_14 === 'No' || $_14 === '' || $_14 === 'Ya tenía un negocio') {		  
		  $form_state['values']['16'] = '';
		  $form_state['values']['17'] = '';
		  $form_state['values']['13_2'] = '';
		  $form_state['values']['14_1'] = '';		  
		}
		
		if ($_13 === 'Sí' && $_14 === 'Sí') {
		  if (empty($_16)) {
		    form_error($form['credits']['16'], t('17. ¿Si ya tenías un negocio, consideras que después del soporte de Alerta Joven ha mejorado?: Campo requerido'));
		  }
		} else {
		  $form_state['values']['16'] = '';
		}
		
		if ($_14 === 'Sí' && $_16 === 'Sí') {
		  if (empty($_17)) {
		    form_error($form['credits']['17'], t('18. ¿Cómo ha mejorado?: Campo requerido'));
		  }
		} else {
		  $form_state['values']['17'] = '';
		}
		
		if ($_13 === 'Sí' && $_14 === 'Sí' &&$_16 === 'Sí') {
		  if (empty($_13_2)) {
		    form_error($form['credits']['13_2'], t('19. ¿Qué monto genera tu negocio mensualmente?: Campo requerido'));
		  }
		} else {
		  $form_state['values']['13_2'] = '';
		}
		
		if ($_13 === 'Sí' && $_14 === 'Sí' && $_16 === 'Sí') {
		  if (empty($_14_1)) {
		    form_error($form['credits']['14_1'], t('20. ¿A qué se dedica tu negocio?: Campo requerido'));
		  }
		} else {
		  $form_state['values']['14_1'] = '';
		}
		
	} else {
	    $form_state['values']['4_3'] = '';
		$form_state['values']['4'] = '';
		$form_state['values']['4_2'] = '';
		$form_state['values']['4_1'] = '';
		$form_state['values']['4_1Otro'] = '';
		$form_state['values']['5'] = '';
		$form_state['values']['6'] = '';
		$form_state['values']['6Otro'] = '';
		$form_state['values']['7'] = '';
		$form_state['values']['8'] = '';
		$form_state['values']['8_1'] = '';
		$form_state['values']['8_2'] = '';
		$form_state['values']['8_2Otro'] = '';
		$form_state['values']['8_0'] = '';
		$form_state['values']['13'] = '';
		$form_state['values']['13_1'] = '';
		$form_state['values']['13_2'] = '';
		$form_state['values']['14'] = '';
		$form_state['values']['14_1'] = '';
		$form_state['values']['15'] = '';
		$form_state['values']['16'] = '';
		$form_state['values']['17'] = '';		
	}
	
	if ($_4_3 === 'Otro') {
	  if (empty($_4_3Otro)) {
	    form_error($form['laboral']['4_3Otro'], t('1.1.Otro (favor especificar): Campo requerido'));
	  }
	} else {
	  $form_state['values']['4_3Otro'] = '';
	}
	
	if ($_4_1 === 'Otro') {
	  if (empty($_4_1Otro)) {
	    form_error($form['laboral']['4_1Otro'], t('4.1.Otro (favor especificar): Campo requerido'));
	  }
	} else {
	  $form_state['values']['4_1Otro'] = '';
	}

	if ($_6 === 'Otro') {
		if (empty($_6Otro)) {
			form_error($form['laboral']['6Otro'], t('4.Otro (favor especificar): Campo requerido'));
		}
	} else {
		$form_state['values']['6Otro'] = '';
	}
	
	if ($_8_2 === 'Otro') {
	  if (empty($_8_2Otro)) {
	    form_error($form['laboral']['8_2Otro'], t('13.Otro (favor especificar): Campo requerido'));
	  }
	} else {
	  $form_state['values']['8_2Otro'] = '';
	}
	print($form_state['values']['16']);
	
 }

 /**
  * Implements the hook_permissions
  */
 function ajlabor_permission() {
	return array(
		'access ajlabor content' => array(
				'title' => t('Access content for ajlabor module'),
				'description' => t('Control the access for the Labor Survey form'),
		)
	);
 }

 /**
  *  Callback function that generates content
  */
function _ajlabor_page() {
	return drupal_get_form('ajlabor_form');
}

/**
 * Script to insert the new form data
 */
function _ajlabor_insert_data(
            $_0,    
			$_1,
            $_4_3,
            $_4_3Otro,
			$_4,
            $_4_4,
            $_4_5,
            $_4_2,
			$_4_1,
            $_4_1Otro,
			$_5,
			$_6,
			$_6Otro,
			$_7,
			$_8,
			$_8_1,
            $_8_2,
            $_8_2Otro,
            $_8_0,
			$_13,
            $_13_1,
            $_13_2,
			$_14,
            $_14_1,
            $_15,
            $_16,
            $_17,
            $_18,
			$uuid,
			$provider_id) {
	
	global $user;
	$currentDate = format_date(time(), 'custom', 'Y-m-d H:i:s');
	$fechaDeLlenado = format_date(strtotime($_0['year'].'-'.$_0['month'].'-'.$_0['day']), 'custom', 'Y-m-d H:i:s');

	$tableFields =  array(
		'user_name' => $user->name,
	    '0_fechadellenado' => $fechaDeLlenado,	  
		'1_HasparticipadoenalguncursodelproyectoAlerta' => $_1,
	    '4_3Cualcursorealizaste' => $_4_3,
	    '4_3Otrofavorespecificar' => $_4_3Otro,
		'4_Actualmentetienesuntrabajoenel' => $_4,
	    '4_4Nombredelaempresa' => $_4_4,
	    '4_5Telefonodelaempresa' => $_4_5,
	    '4_2Esestetuprimerempleo' => $_4_2,
		'4_1Quehacesenesetrabajo' => $_4_1,
	    '4_1Otrofavorespecificar' => $_4_1Otro,
		'5_Cuantotiempotienesenestetrabajo' => $_5,
		'6_Estetrabajoes' => $_6,
		'6_Otrofavorespecificar' => $_6Otro,
		'7_Cuantoganasenunasemana' => $_7,
		'8_Cuandoiniciasteelcursotecnicoyaestabas' => $_8,
		'8_1Considerasquetutrabajoactual' => $_8_1,
	    '8_2Porqueconsideraqueesunmejorempleo' => $_8_2,
	    '8_2Otrofavorespecificar' => $_8_2Otro,
	    '8_3Cambiastedelugardetrabajodespues' => $_8_0,	   
		'13_Hasrecibidounprestamoatravesdelproyecto' => $_13,
	    '13_1Quemontorecibiste' => $_13_1,
	    '13_2Quemontogeneratunegociomensualmente' => $_13_2,
		'14_Tienesunnegociopropio' => $_14,
	    '14_1Aquesededicatunegocio' => $_14_1,
	    '15_Quetipodeapoyo' => $_15,
	    '16_Siyateniasunnegocioconsiderasquedespuesdel' => $_16,
	    '17_Comohamejorado' => $_17,
	    '18_Quiencontactoalparticipante' => $_18,
	);
	
	if(_ajlabor_alreadyExist($uuid)) { // Updating existing labor form
		$tableFields['changed'] = $currentDate;
		$labor_entry = db_update('aj_labor')->fields($tableFields)->condition('uuid', $uuid);
		$labor_entry->execute();
	} else { // creating new labor form entry
		$tableFields['created'] = $currentDate;
		$tableFields['uuid'] = $uuid;
		$tableFields['provider_id'] = $provider_id;
		$labor_entry = db_insert('aj_labor')->fields($tableFields);
		$labor_entry->execute();
	}
}

/**
 * Get the beneficiary info
 */
function _ajlabor_getBeneficiaryInfo($uuid) {

	$query = db_select('aj_registration', 'reg');
	$query->fields('reg', array('nombre', 'apellido', 'uuid'));
	$query->condition('uuid', $uuid);
	$query->orderBy('nombre', 'ASC');
	$query->addExpression("DATE_FORMAT(FROM_DAYS(DATEDIFF(DATE_FORMAT(NOW(), '%Y-%m-%d'), dob)), '%Y')+0", 'edad');
	$query->range(0,1);

	$result = $query->execute();
	return $result->fetchAssoc();
}

/**
 * Checks if the beneficiary meets the requierent to have a labor form entry
 */
function _ajbeneficiaryEligible($uuid) {
	
	$targetPrograms = [2, 3, 18, 22]; // Autoempleo, CTV, Microcréditos, La Compañía
	
	$query = db_query(
			'SELECT uuid
			FROM {aj_attendance}
			JOIN {field_data_field_activity_program} on aj_attendance.activity_id = field_data_field_activity_program.entity_id
			JOIN {field_data_field_program_name} on field_data_field_program_name.entity_id = field_data_field_activity_program.field_activity_program_target_id
			JOIN {field_data_field_programname_name} on field_data_field_programname_name.entity_id = field_data_field_program_name.field_program_name_target_id
			WHERE uuid = :uuid 
				and field_data_field_programname_name.entity_id in (:targetPrograms)', 
			array(':uuid' => $uuid,
				  ':targetPrograms' => $targetPrograms
			));
	$result = $query->fetchField(0);

	if ($result) {
		return true;
	}
	
	return false;
}

function _ajlabor_isEditable($uuid) {
	$today6MonthsAgo = format_date(strtotime('3 months ago'), 'custom', 'Y-m-d H:i:s');
	// 			and :today6MonthsAgo <= created
// 	':today6MonthsAgo' => $today6MonthsAgo,
	

	$query = db_query(
			'SELECT uuid
			FROM {aj_labor}
			WHERE uuid = :uuid 
			and 4_Actualmentetienesuntrabajoenel = :actualmenteTienesTrabajoActual
			and 9_Enlosultimos12meseshashecho = :trabajoEnLos12Meses',
			array(':uuid' => $uuid,
					':actualmenteTienesTrabajoActual' => 'No',
					':trabajoEnLos12Meses' => 'No'
			));
	
	$result = $query->fetchField(0);
	
	if ($result) {
		return true;
	}
	
	return false;
}

function _ajlabor_getExistingLaborForm($uuid) {
	$query = db_query(
			'SELECT * 
			FROM {aj_labor}
			WHERE uuid = :uuid',
			array(
					':uuid' => $uuid
			));
	return $query->fetchAssoc();
}

/**
 * Checks if a given uuid already has a labor entry in the database
 */
function _ajlabor_alreadyExist($uuid) {

	$query = db_select('aj_labor', 'ajlabor');
	$query->fields('ajlabor', array('uuid'));
	$query->condition('uuid', $uuid);
	$query->range(0,1);

	$result = $query->execute();
	$entry =  $result->fetchAssoc();

	return !empty($entry);
}
