// Generated by CoffeeScript 1.6.3
(function(document) {
  if (document.collection === "result" &&  (document.Estecolateralparticipante === "Sí" || document.Estecolateralparticipante === "Indirecto"  )) {
    if (document.Completado === "true") {
      return emit(document.question + ':true:' + document.lastModifiedAt, null);
    } else {
      return emit(document.question + ':false:' + document.lastModifiedAt, null);
    }
  }
});

/*
//@ sourceMappingURL=map.map
*/