// Generated by CoffeeScript 1.6.3
(function(doc) {
  if (doc.question === "Participant Survey-es" && doc.Completado === "true" && doc.convertedDate === void 0) {
    return emit(doc.uuid + "$" + doc.lastModifiedAt, null);
  }
});

/*
//@ sourceMappingURL=map.map
*/
