// Generated by CoffeeScript 1.6.3
(function(doc) {
  if (doc.question === "Participant Survey-es" && (doc.provider_id === void 0 || doc.provider_id === null || doc.provider_id === "")) {
    return emit(doc.uuid, null);
  }
});

/*
//@ sourceMappingURL=map.map
*/
