// Generated by CoffeeScript 1.6.3
(function(doc) {
  if (doc.question === "Participant Registration-es" && doc.Completado === "true" && (doc.Estecolateralparticipante === void 0 || (doc.Estecolateralparticipante !== "Sí" && doc.Estecolateralparticipante !== "Indirecto"))) {
    return emit(doc.uuid, null);
  }
});

/*
//@ sourceMappingURL=map.map
*/
