// Generated by CoffeeScript 1.6.3
(function(doc) {
  var val;
  val = "";
  val += '"Nombre":"' + doc.Nombre + '"';
  val += ',' + '"Apellido":"' + doc.Apellido + '"';
  val += ',' + '"Question":"' + doc.question + '"';
  val += ',' + '"UUID":"' + doc.uuid + '"';
  if (doc.question === "Participant Registration-es" || doc.question === "Participant Registration-es-DUPLICATE") {
    return emit(doc.Nombre, "{" + val + "}");
  }
});

/*
//@ sourceMappingURL=map.map
*/
