// Generated by CoffeeScript 1.9.2
(function(document) {
  if (document.collection === "result" && (document.Estecolateralparticipante === void 0 || (document.Estecolateralparticipante !== "Sí" && document.Estecolateralparticipante !== "Indirecto"))) {
    if (document.Completado === "true") {
      return emit(document.question + ':true:' + document.lastModifiedAt, null);
    } else {
      return emit(document.question + ':false:' + document.lastModifiedAt, null);
    }
  }
});

//# sourceMappingURL=map.js.map
