// Generated by CoffeeScript 1.6.3
(function(doc) {
  if (doc.question === "Participant Registration-es" && (doc.provider_id === "undefined" || (doc.provider_id == null)) && ((doc.provider_name == null) || doc.provider_name === "undefined")) {
    return emit(doc.uuid, doc.id);
  }
});

/*
//@ sourceMappingURL=map.map
*/


(function(doc) {
  if (doc.question === "Participant Survey-es" && (doc.provider_id == "undefined" || doc.provider_id == null ) ) {
    return emit(doc.uuid, doc.id);
  }
});