<?php
/**
 * @file
 * A chron module to create custom tables and load data from CouchDb into these tables.
 */

error_reporting(E_ALL);
ini_set("display_errors", 1);





/**
 * Cron job is creating the queue cron job.
 *
 */
function ajetlexit_cron() {

    $queue = DrupalQueue::get('ajetlexit');
    $queue->createItem("arg1");
}

/**
 * Cron jobs info.
 *
 * @return array
 */
function ajetlexit_cron_queue_info()
{

    watchdog("ajetlexit", "INSIDE CRON QUEUE INFO");

    $queues = array();

    //cron is run at 2:00am
    //if(date('G')==2)
    //{
    $queues['ajetlexit'] = array(
        'worker callback' => 'load_exit_worker',
        'time' => 300, // time in seconds, this is the duration that the job will be CALLED, e.g.
        // after it finish it will be called again until the time is up.
    );
    //}

    return $queues;
}


/**
 * The queue job worker. Query registration from couchDB descending and load them into mySQL database.
 *
 */
function load_exit_worker()
{
    //watchdog("ajetlexit", "load_exit_worker JOB IS CALLED");

    ajetllog_log("ajetlexit", "MESSAGE", "PROCESSING STARTED");

    global $base_url;

    // set module global variables
    ajetlexit_setModuleVariables();

    $req_url = 'http://localhost:5984/coconut/_design/coconut/_view/resultsByQuestionAndComplete?startkey=%22Exit%20Survey-es%3Atrue%3Az%22&endkey=%22Exit%20Survey-es%3Atrue%22&descending=true&include_docs=false';

    //TBD Uncomment when deploying to prod, the $base_url is not write when deploying on Windows because it has /drupal in the link
    //$req_url = $base_url.':5984/coconut/_design/coconut/_view/resultsByQuestionAndComplete?startkey=%22Participant%20Registration-es%3Atrue%3Az%22&endkey=%22Participant%20Registration-es%3Atrue%22&descending=true&include_docs=false';

    // prepare the request options
    $req_options = array(
        'method' => 'GET',
        'headers' => array(
            'Content-Type' => 'application/json'
        ));

    // query couchdb data
    $couch_response = drupal_http_request( $req_url, $req_options );

    // decode to json objects
    $rows = drupal_json_decode( $couch_response->data)['rows'];

    $size = sizeof($rows);

    ajetllog_log("ajetlexit", "MESSAGE", "******Rows fetched:".$size);

    $i = 0;

    foreach ( $rows as $one_row ){
        list($type, $isCompleted, $lastModified1,$lastModified2, $lastModified3, $lastModified4) = explode(":", $one_row['key']);


        // lastModified is in format as 2014-08-11T13:50:41-03:00 so need to re-create
        $lastModified = $lastModified1.':'.$lastModified2.':'.$lastModified3.':'.$lastModified4;

        // check if the record with the same id and last modified date already exist
        $record = ajetlexit_getExitByIdAndModifiedDate($one_row['id'], $lastModified);

        if ($record != null) {
            ajetllog_log("ajetlexit", "MESSAGE", "Found same exact record and stopped loading exit forms.");
            break;
        }


        ajetlexit_loadExit($one_row['id'], $lastModified);
        $i++;


        /*if ($i === 1000)
            break;*/

    }

    ajetlexit_deleteModuleVariables();
    ajetllog_log("ajetlexit", "MESSAGE", "Document processed".$i);

}



/**
 * Implement hook_enable()
 */
function ajetlexit_enable() {
    //Check if table exists, if not install the schema.
    /* if(db_table_exists('aj_exit') == FALSE) {
         drupal_install_schema('aj_exit');
     }*/


}


/**
 * Delete module variables.
 */
function ajetlexit_deleteModuleVariables(){
    variable_del("ajExitColumns");
    variable_del("exitColumnMap");
}

/**
 *
 * Use variable_set() to set module global variables.
 *
 *
 */
function ajetlexit_setModuleVariables(){
    // retrieve aj_exit table columns
    $ajExitColumns = drupal_schema_fields_sql("aj_exit");
    // set the columns as variable
    variable_set("ajExitColumns", $ajExitColumns);

    /**
     * These is mapping for columns for column name - exit form document key. We need that
     * because the column names were becoming too big. The mySQL limit is 64 characters but
     * it looks kind of ugly when they are so long.
     */
    $exitColumnMap = array("9Conseguistetuactade"=>"9ConseguistetuactadenacimientoluegodeentraraAlertaJoven",
        "15ACuántasveceshassido"=>"15ACuántasveceshassidotransportadoporlapolicía",
        "15BCuántasveceshassido"=>"15BCuántasveceshassidoarrestadoporlapolicía",
        "15CCuántasveceshassido"=>"15CCuántasveceshassidoacusadodecometeralgúndelitoenlafiscalíaopolicía",
        "15DCuántasveceshassidoenviado"=>"15DCuántasveceshassidoenviadoauncentrodeatenciónintegral",
        "16Enquémedidatuvidaha"=>"16Enquémedidatuvidahasidoafectadaporladelincuencia",
        "11Estasactualmente"=>"11Estasactualmenteasistiendoaunaescuelaouniversidad",
        "12Hascompletadoa"=>"12HascompletadoalgúncursotécnicoluegodeentraraAlertaJoven",
        "18Laúltimavez"=>"18Laúltimavezquetuvisterelacionessexualestúotucompañeroautilizócondón",
        "19Laúltimavez"=>"19Laúltimavezquetuvisterelacionessexualescuálmétodousasteotucompañeroaparaprevenirelembarazo",
        "21Siquisierastenersexo"=>"21Siquisierastenersexocreesqueseríascapazdeconvenceratuparejaqueuseuncondónencasoqueélellanoquiera",
    	"9APorQueNoTienesActaDeNacimiento"=>"9ASinocuáleslarazónprincipalporlaquenotienesunactaMarcasólounaopción",

    );

    variable_set("exitColumnMap", $exitColumnMap);
}
/**
 * Opens the document by Id and returns the JSON object.
 *
 * @param $id
 */
function ajetlexit_openDocById($id){
    // TBD: changed hard coded localhost link
    $req_url = 'http://localhost:5984/coconut/'.$id;

    $req_options = array(
        'method' => 'GET',
        'headers' => array(
            'Content-Type' => 'application/json'
        ));

    $couch_response = drupal_http_request( $req_url, $req_options );
    $doc = drupal_json_decode( $couch_response->data);


    return $doc;

}

/**
 * Generates the first insert query e.g. .(col1, col2, col3...). It's driven by the aj_exit table columns.
 *
 * @param $doc
 *
 */
function ajetlexit_genInsertQueryPart1($doc){
    $query = "";

    $ajExitColumns = variable_get("ajExitColumns");



    foreach ($ajExitColumns as $col){
        if ($col === "id" || $col === "changed")
            continue;

        $query = $query.$col.", ";


    }

    // clean the last ","
    $len = strlen($query);
    $query =substr($query, 0, $len-2);

    return $query;

}


/**
 * Generates the values() insert statement.
 *
 * @param $doc
 *
 */
function ajetlexit_genInsertQueryPart2($doc){
    $query = "";
    $key = "";
    $val = "";

    $ajExitColumns = variable_get("ajExitColumns");
    $exitColumnMap = variable_get("exitColumnMap");

    foreach ($ajExitColumns as $col) {
        // skip these
        if ($col === "id" || $col === "changed")
            continue;

        if (array_key_exists($col, $exitColumnMap))
            $key = $exitColumnMap[$col];
        else
            $key = $col;

        if ($key === "createdAt" || $key === "lastModifiedAt") {
            $val = ajetlexit_couchDateTime2Mysql($doc[$key]);
            $query = $query . $val . " ";
        }else if ($key === "created"){
            $val = " NOW() ";
            $query = $query . $val . " ";
        }else if ($key === "22FechadeRevisión"){
            $val = ajetlexit_couchDate2Mysql($doc[$key]);
            $query = $query . $val . " ";
        }else {
            if (is_array($val)){
                $val = $val[0];
            }
            if (array_key_exists($key, $doc)) {
                //Support for  fields that is one value but it's stored as an array
                if (is_array($doc[$key])) {
                    foreach ($doc[$key] as $v){
                        //ajetllog_log("ajetlexit", "MESSAGE", "VAL 0 is " . $v);
                        $val = $v;
                    }
                }else
                    $val = $doc[$key];

                $pos = stripos($val, "'");
                if ($pos > 0)
                    $val = str_replace("'", "\'", $val);

            }else {
                $val = "";
            }
            $query = $query . "'" . $val . "' ";
        }




        $query = $query.",";


    }

    // clean the last ","
    $len = strlen($query);
    $query =substr($query, 0, $len-1);

    return $query;

}


/**
 * Inserts data into aj_exit table.
 *
 * @param $id
 * @param $lastModifiedDate
 */
function ajetlexit_insertExit($doc){
    $q1 = ajetlexit_genInsertQueryPart1($doc);
    $q2 = ajetlexit_genInsertQueryPart2($doc);
    $query = "INSERT INTO {aj_exit} (".$q1.") VALUES(".$q2.")";

    try{
        $result = db_query($query);
    }catch(Exception $e){
        ajetllog_error("ajetlexit", "MySQL ERROR", "MySQL error.", $e->getMessage(), "");
    }
}

/**
 * Inserts uuid-provider_id-program_id data. The program questions are in format like
 * 14HascompletadoalgúnoalgunosdeestosprogramasestandoenAlertaJovenMarcatodaslasqueapliquen_1
 * 14HascompletadoalgúnoalgunosdeestosprogramasestandoenAlertaJovenMarcatodaslasqueapliquen_2
 * ........................................................................................_N
 *
 * @param $doc
 */
function ajetlexit_insertExitParticipants($doc){
    $programQ = "14HascompletadoalgúnoalgunosdeestosprogramasestandoenAlertaJovenMarcatodaslasqueapliquen";

    //ajetllog_log("ajetlexit", "DEBUG", "Inside insertParticipants");

    // first delete in case of records for this uuid already exist
    $dq ="DELETE FROM {aj_exit_programs} WHERE uuid='".$doc['uuid']."'";
    db_query($dq);


    $len = strlen($programQ);
    foreach ($doc as $key=>$value) {
        $pos = strpos($key, $programQ);
        if ($pos === 0) {
            // retrieve the program id
            $programId = substr($key, $len + 1);
            $answer = $doc[$key];
            $query = "INSERT INTO {aj_exit_programs} (_id, uuid, provider_id, program_id, answer, created) VALUES('".$doc['_id']."','".$doc['uuid']."','".$doc['provider_id']."','".$programId."','".$answer."', NOW())";

            try{
                $result = db_query($query);
            }catch(Exception $e){
                ajetllog_error("ajetlexit", "MySQL ERROR", "MySQL error.", $e->getMessage(), "");
            }
        }
    }

}



/**
 * Query aj_exit table for record by _id and lastModifiedAt date.
 *
 * @param $_id
 * @param $lastModifiedAt
 * @return null if record does not exist
 *         the record if exist
 */
function ajetlexit_getExitByIdAndModifiedDate($_id, $lastModifiedAt)
{
    $retRecord = null;

    $sqlLastModifiedAt = ajetlexit_couchDateTime2Mysql($lastModifiedAt);

    $result = db_query("SELECT t.id FROM {aj_exit} t WHERE t._id = :_id AND t.lastModifiedAt=".$sqlLastModifiedAt, array(':_id' => $_id));


    if ($result == null) {
        return null;
    }

    foreach ($result as $record) {
        $retRecord = $record;
        break;
    }

    return $retRecord;

}

/**
 * Query aj_exittable by _id.
 *
 * @param $_id
 * @return null if record not found
 *         the record if found
 */
function ajetlexit_getExitById($_id)
{
    $retRecord = null;
    $result = db_query('SELECT t.id, t._id, t.lastModifiedAt FROM {aj_exit} t WHERE t._id = :_id', array(':_id' => $_id));

    if ($result == null) {
        return null;
    }

    foreach ($result as $record) {
        $retRecord = $record;
        break;
    }

    return $retRecord;


}


/**
 * Query aj_exit table by _id and lastModifiedAt DIFFERENT then the input $lastModifiedAt.
 *
 * @param $_id
 * @param $lastModifiedAt
 * @return null if record is not found
 *         the record if found
 */
function ajetlexit_getExitByIdDifferentDate($_id, $lastModifiedAt)
{
    $retRecord = null;
    $sqlLastModifiedAt = ajetlexit_couchDateTime2Mysql($lastModifiedAt);
    $result = db_query("SELECT t.id FROM {aj_exit} t WHERE t._id = :_id AND t.lastModifiedAt<>".$sqlLastModifiedAt, array(':_id' => $_id));


    if ($result == null) {
        return null;
    }

    foreach ($result as $record) {
        $retRecord = $record;
        break;
    }

    return $retRecord;



}

/**
 * First it checks for same _id AND different lastModifiedAt date. If record found
 * deletes the record before inserting the modified document. If record is not found
 * insert the data into the aj_exit table.
 *
 * @param $id
 * @param $lastModifiedDate
 */
function ajetlexit_loadExit($_id, $lastModifiedAt){

    // check if the record with the same id but different modified date already exist
    $record = ajetlexit_getExitByIdDifferentDate($_id, $lastModifiedAt);

    // TBD: Maybe need to update the existing document, not delete before inserting. However because
    // of the fast approaching deadline do this for now.

    // record has been changed so delete the old record before inserting
    if ($record != null) {
        db_query("DELETE FROM {aj_exit} WHERE _id='".$_id."'");
    }

    // fetch the document from couch db
    $doc = ajetlexit_openDocById($_id);

    // return if document is not valid
    if (!validate($doc))
        return;

    // insert the record
    ajetlexit_insertExit($doc);

    // insert participant - program relationship
    ajetlexit_insertExitParticipants($doc);
}


/**
 * Returns false if document is missing some required fields such as "Fecha de Revisión"
 *
 * @param $doc
 *
 */
function validate($doc){

    $key = "22FechadeRevisión";
    if (!array_key_exists($key, $doc) || $doc[$key] === null || $doc[$key] === "") {
        ajetllog_log("ajetlexit", "ERROR", "Document with id=".$doc['_id']." not inserted bacuse Fecha de Revision is missing.");
        return false;
    }

    return true;
}


/**
 *
 * Removes the last 6 characters (the timezone) from couchDB date.
 *
 * Example: converts 2013-11-29T09:40:10-03:00 to 2013-11-29T09:40:10 and
 * adds STR_TO_DATE so the final string will be STR_TO_DATE('2013-11-29T09:40:10', '%Y-%m-%dT%H:%i:%S').
 *
 */
function ajetlexit_couchDateTime2Mysql($dt){

    // remove the last 6 chars, e.g. the couchDB time zone
    $len = strlen($dt);
    $dt = substr($dt, 0, $len - 6);

    return " STR_TO_DATE('".$dt."', '%Y-%m-%dT%H:%i:%S')";
}


/**
 *

 * Example: converts 23/10/2013 to STR_TO_DATE('23/10/2013', '%d/%m/%Y').
 *
 * Handle different date formats. The input date might be in format:
 * 23-07-2014
 * 2014-07-23
 * 23/04/2014
 *
 */
function ajetlexit_couchDate2Mysql($dt){
    if ($dt == null )
        return " null ";

    $pos = stripos($dt, "octubre");

    if ($pos > 0){
        list($dd, $mm, $y) = explode("-", $dt);
        if (strlen($dd) == 1)
            $dd = '0'.$dd;
        if($mm === "octubre")
            $mm = '10';
        $newDt = $dd.'-'.$mm.'-'.$y;
        return " STR_TO_DATE('".$newDt."', '%d-%m-%Y')";
    }


    // date is in dd/mm/YYYY format
    $pos = stripos($dt, "/");

    if ($pos > 0)
        return " STR_TO_DATE('".$dt."', '%d/%m/%Y')";

    $pos = stripos($dt, "-");

    if ($pos > 0) {

        if (strlen($dt) < 8)
            return " null ";

        $pos1 = stripos($dt, "-");
        if ($pos1 === 2) // date is in format 23/05/2014
            return " STR_TO_DATE('" . $dt . "', '%d-%m-%Y')";
        else {

            $first5 = substr($dt, 0, 5);
            $last4 = substr($first5, 1);

            // it means the year has one additional character on front, e.g. 22014, 32014, etc..
            if ($last4 === "2014" || strstr($dt, '20104') || strstr($dt, '20147') || strstr($dt, '20014')){
                $endDt = substr($dt, 5);
                $dt = '2014'.$endDt;
            }else if ($last4 === "2013" || strstr($dt, '20103') || strstr($dt, '20137') || strstr($dt, '20013')){
                $endDt = substr($dt, 5);
                $dt = '2013'.$endDt;
            }


            return " STR_TO_DATE('" . $dt . "', '%Y-%m-%d')";
        }
    }else{
        //assume date is in 14032014 format
        return " STR_TO_DATE('" . $dt . "', '%d%m%Y')";
    }
}





