// Generated by CoffeeScript 1.6.3
(function(doc) {
  if (doc.question === "Participant Registration-es" && doc.Completado === "true" && doc.hasOwnProperty('provider_id')) {
    return emit(doc.provider_id, doc);
  }
});

/*
//@ sourceMappingURL=map.map
*/
