// Generated by CoffeeScript 1.6.3
(function(document) {
  if (document.collection === "result" && (document.provider_id === void 0 || document.provider_id === null) ){
    if (document.Completado === "true") {
      return emit(document.question + ':true:' + document.lastModifiedAt, null);
    } else {
      return emit(document.question + ':false:' + document.lastModifiedAt, null);
    }
  }
});